baresip/re

- src/tcp/tcp.c
As mentioned here:
https://docs.microsoft.com/en-us/windows/win32/api/winsock/nf-winsock-recv
For WSAECONNRESET and WSAECONNABORTED:
`The application should close the socket as it is no longer usable.`
Fixes never-ending recv handler warnings.
> tcp: close socket on windows if connection is aborted or reset

- include/re_tls.h
- src/tls/openssl/tls.c
- src/tls/openssl/tls.h
These functions are requiered for barsip PR [#1078](https://github.com/baresip/baresip/pull/1078)
> tls: functions to get the certificate issuer and subject

- include/re_http.h
- include/re_tcp.h
- src/http/client.c
- src/tcp/tcp_high.c
Bind socket to local address allows us to use specific network interfaces for http requests (e.g. for a VPN).
This is used by a baresip http request module. We could make a PR for this module for baresip if required.
> Http request bind laddr

- include/re_sipreg.h
- src/sipreg/reg.c
Cisco REGISTER keep-alive is only a name for a periodic un-REGISTER, this is nothing more than a REGISTER with expires=0. A SIP proxy that is available answers to these un-REGISTER requests and thus the UA is able to track the availability of a proxy without having to register to it.
This is useful for a setup with a main SIP proxy and fallback proxies. Initially the registration is only done for the main proxy. The availability of the fallback proxy can be tracked by the Cisco REGISTER keep-alives.
The https://github.com/baresip/baresip/pull/1083 is based on this PR.
> Cisco register keep alive

- src/main/main.c
Not ready, needs some rewrites and more tests.
> Fix windows fd

- .gitignore
- mk/win32/re.vcxproj
- mk/win32/re.vcxproj.filters
- src/dns/client.c
Adding missing files to project.
Add HAVE_INET6 def check around dns listener
Updated .gitignore with visual studio build folders
> dns/client: fix HAVE_INET6 and win32/vcxproj: updates

- include/re_dns.h
- include/re_http.h
- include/re_httpauth.h
- include/re_tls.h
- src/dns/client.c
- src/http/client.c
- src/http/mod.mk
- src/http/request.c
- src/httpauth/basic.c
- src/httpauth/digest.c
- src/httpauth/mod.mk
- src/tls/openssl/tls.c
Adds client side basic and digest authorization and HTTP request code (request.c) that combines these with http_cli (client.c) in order to provide a higher level interface for performing HTTP request. Supports:
- GET, POST, PUT, ... requests (HTTP method can be specified.)
- basic, digest and bearer authentication
- TLS
This new high level API should be usable from:
- baresip https://github.com/baresip/baresip/pull/1099 and
- directly by applications depending on libre (without baresip). Example: https://github.com/baresip/retest/pull/5
Tested with:
- https://ptsv2.com/
- https://jigsaw.w3.org/HTTP/
- https://httpbin.org/#/
This PR is related to PR https://github.com/baresip/baresip/pull/1099.
> add HTTP request connection with authorization

- src/http/request.c
Keep an internal reference. The user may deref his reference immediately after
calling http_reqconn_send().
Previous solution suggests that the application derefs the instance in its response handler. But this lead to a segfault in line:
```
245  conn->tc = mem_deref(conn->tc);
```
Now deref immediately after http_reqconn_send() or later in the response handler is possible.
> http: fix segfault in response.c

- src/http/client.c
- src/http/request.c
- Fixes segfault if http_reqconn_send() is called with NULL parameter.
- Activates hostname check for http_cli in general.
- Enables parallel HTTPS requests.
> http: fixes memleak, segv and hostname check for http_cli and http_reqconn

- include/re_http.h
- src/http/client.c
-   Adds struct http_conf and function http_client_set_config in order to be able to set connection timeout, receive timeout and idle timeout for the TCP socket.
Previously only timeouts for the DNS resolution were supported.
-  Sets the URL path to "/" if it is empty.
> http_cli: HTTP client timeout and default path

- include/re_tls.h
- src/tls/openssl/tls.c
A new function to generate a self signed cert using elliptic curve cryptographic primitives.
The used elliptic curve is hardcoded with NID_secp521r1. 
One can use this function in the barsip dtls_srtp module.
> tls: set selfsigned Elliptic Curve (EC) function

- src/http/client.c
The request of the connection must be set to NULL at req_close.
Wrong checks in conn_idle would lead to not start the idle_timeout
and the request of the connection would not be set to NULL.
At TCP connection close, close_handler & try_next is called with
ECONNRESET. This would lead to a ptr deref in try_next of conn->req
which is valid data, but the req itself is not valid anymore.
conn_req is not a NULL ptr so the check if (!req) is not effective.
Following the next line, one sets a nonvalid data segment (req->conn) -> SEGV.
> http: fix ptr of conn and request at req_close

- src/http/request.c
The http request code should not handle any TCP&TLS connections. Beside mem_ref and mem_deref nothing special happens with the connections. Connection handling by the http client is sufficient and prevents memory problems.
For each request sent, the reference counter of a http_reqconn is incremented. Therefore, we have to ensure a decrementation of the counter for each handled response.
> Http request mem leak

- src/sipreg/reg.c
The dialog will stop after sending the REGISTER with expires=0
(de-register). So the 401 unauthorized response does not trigger another
REGISTER as it would usually be the case.
So in order to allow proper de-register, include auth in this case.
> sipreg: skip digest challenge for de-register

- docs/jbuf/README.md
- docs/jbuf/jbuf.plot
- include/re_jbuf.h
- src/jbuf/jbuf.c
This PR introduces an adaptive jitter buffer algorithm.
The existing jbuf is extended.
- Make functions jbuf_get/jbuf_put thread safe.
- Add silence flag that has to be set by application (baresip) after decoding.
- Compute jitter like RFC3550 (RTP) or wireshark.
- Increase number of packets during silence in jbuf_get() by returning nothing.
- Reduce number of packets by a second immediate jbuf_get(). After decoding baresip drops a frame during silence to reduce the latency again.
- Adds wish size for the start of the stream.
- docs: add jbuf folder to docs with README and gnuplot
This plot shows that with a view buffer manipulations (the red dots) the average buffer size (avbuftime) can be kept between the boundaries. At 10 seconds the network jitter starts and at 25 seconds the jitter …
> Adaptive jbuf

- include/re_tls.h
- src/http/client.c
- src/tls/openssl/tls.c
- The function tls_set_verify_server() should be extended by SNI (hostname verification).
- Currently only used for rtmp. But this doesn't hurt because IP-addresses are excepted from this change. And for domains it makes sense to check the hostname.
- The function tls_set_verify_server() now also is used for HTTP clients.
- The function tls_set_verify_client() only activates certificate verification that accepts all certificates. It is used only in baresip module dtls_srtp. We do not touch this here, but want to rename the verify-handler to "verify_trust_all()".
TODO (but in another PR):
- For SIP/TLS this function should be called for each TLS connection once. Maybe then it should be renamed to tls_set_verify_peer().
> HTTP SNI check

- mk/re.mk
- src/hash/func.c
- src/http/request.c
- src/main/openssl.c
- src/rtmp/conn.c
- src/sip/transp.c
> Cleanup mk/re.mk

- README.md
- mk/re.mk
Adding C11 detection (gcc/clang 5.x and newer). It can be disabled with `make CC_C11=`.  When C11 is detected, it defines `HAVE_ATOMIC`. This can also be disabled with `make HAVE_ATOMIC=`.
Fallback tested on centos 7 with gcc 4.x and clang 3.x (`clang -dumpversion` shows 4.x gcc compatibility version and not the real version).
> mk/re: add C11 and Atomic detection

- mk/re.mk
These days again we are playing around with optimizing/simplifying our yocto recipes. Same for a very old buildroot system. We always run in problems that libre is detected on the build/devel host and paths are set in-correctly.
This two commits repair two possibilities to set the paths to libre, which we think solve cross compilation problems.
1. LIBRE_PATH could be set externally. If it is not set, nothing changes the old behavior. So it should not break anything.
2. LIBRE_INC, LIBRE_SO could be used if headers and libre.so is lying on different places. Same here: If it is not set externally, nothing changes.
If the user previously set one of these variables, it had no result.
With this patches it may often be enough to set CC and SYSROOT correctly for cross compilation. Maybe in …
> Re mk cross compile fixes

- mk/re.mk
With Double-Colon Rules you can now extend `make info` in other makefiles.
> mk/re: info double colon rule

- mk/re.mk
Allows a cross compilation build by only setting SYSROOT.
> Re mk cross build2

- mk/re.mk
- src/net/linux/rt.c
- src/tls/openssl/tls.c
This helps to detect such warnings earlier on all platforms, like mentioned here:
https://github.com/baresip/baresip/pull/1159
depends on: https://github.com/baresip/baresip/pull/1170
> clang shorten-64-to-32 warnings

- src/tls/openssl/tls.c
increases the size of the self-signed key/certificate to 2048 bytes.
Recent versions of OpenSSL refuse to use certificates with 1024 byte
RSA signatures.
I ran into this after upgrading ubuntu and SSL_CTX_use_certificate returning an error 1.
https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_get_security_level.html returns 2 on those systems, forbidding 1024 byte keys. The overall security of self-signed certificates is not great but this helper method is convenient :-)
> fix weak self-signed certificates

- src/sip/ctrans.c
- src/sip/request.c
- src/sip/sip.c
- src/sip/sip.h
- src/sip/transp.c
A change in the API of ctrans and transp is necessary. At the
calls between request and ctrans, the hostname information of the
next hop is lost. This information is crucial for SNI, which is set
in transp.
> sip: SIP/TLS Server Name Indication

- include/re_net.h
- src/net/net.c
Especially under windows the selection of the default ip/route is not very reliable. If the new approach fails, it fallbacks to the old mechanisms.
Todo:
> net: get default source addr

- .github/workflows/abi.yml
- Makefile
- debian/libre.files
- debian/rules
@robert-scheck Can you check if soname handling fits your needs/requirements?
@alfredh I saw that you added and reverted a similar change some time ago: https://github.com/creytiv/re/commit/1d191277024abd512491fdcbc270649565bf352d
Are there any problems I should be aware of or i should test?
> mk: add .so name versioning, resolves #32

- src/http/client.c
- src/tls/openssl/tls.c
This fixes an ugly bug when a client certificate should be added for the HTTP client. A illegal pointer is returned, which leads to a illegal mem access.
> http: fix file read for client certificates

- src/tls/openssl/tls.c
Openssl uses two different certificate storages by SSL_CTX_use_certificate_chain_file
The first certificate loaded from a file is saved in a sepparate storage.
Upcoming certificates are located in an extra chain cert storage
> tls: tls_get_issuer/subject return the info of the first loaded cert

- include/re_types.h
- mk/re.mk
Usage example:
```c
#include <re.h>
int fn1(void);
int fn2(void);
int fn3(void);
int fn1(void) {
int err;
err = fn2();
IF_ERR_RETURN(err);
return 0;
}
int fn2(void) {
int err;
err = fn3();
IF_ERR_RETURN(err);
return 0;
}
int fn3(void) {
int err;
err = EINVAL;
IF_ERR_RETURN(err);
return 0;
}
int main(void)
{
int err;
err = fn1();
IF_ERR_GOTO_OUT(err);
return 0;
out:
re_printf("error %d\n", err);
return err;
}
```
`make TRACE_ERR=1`
Output after execution:
```
TRACE_ERR: src/main.c:29: fn3(): Invalid argument (22)
TRACE_ERR: src/main.c:20: fn2(): Invalid argument (22)
TRACE_ERR: src/main.c:11: fn1(): Invalid argument (22)
TRACE_ERR: src/main.c:39: main(): Invalid argument (22)
error 22
```
> add error trace helpers

- include/re_http.h
- src/http/server.c
Add function that resets the timeout timer for a connection of the HTTP server. 
This is required for long lasting requests such as streaming media (MJPEG stream) or file uploads.
> Add function that resets the timeout timer.

- include/re_sip.h
- include/re_sys.h
- include/re_tls.h
- src/sip/transp.c
- src/sys/fs.c
- src/tls/openssl/tls_tcp.c
Description can be found in [baresip/#1376](https://github.com/baresip/baresip/pull/1376)
> Tls sipcert per acc

- include/re_sip.h
- include/re_tcp.h
- include/re_udp.h
- src/sip/sip.h
- src/sip/transp.c
- src/tcp/tcp.c
- src/udp/udp.c
Allows to configure IPv4 ToS value for SIP
Can wait after release of baresip v1.1.0.
> ToS for video and sip

- src/sdp/msg.c
Consider the case e.g. in Session Progress SDP when the port number is zero!
This, means that the media should be deactivated and no attribute lines will
follow in the SDP. In this case the rdir should be set to SDP_INACTIVE.
- Tested with baresip on both sides branch https://github.com/cspiel1/baresip/tree/selective_early_media.
- Had an outgoing call and the peer sends a 183 Session Progress with deactivated audio (early video only).
- In `sdp_decode()` from SDP on the 183 Session Progress the audio rdir should be set to SDP_INACTIVE, which is not done in master.
This fix relates to baresip PR: https://github.com/baresip/baresip/pull/1398
> sdp: in media_decode() reset rdir if port is zero

- include/re_sip.h
- include/re_sipsess.h
- src/sip/sip.h
- src/sipsess/connect.c
- src/sipsess/sess.c
- src/sipsess/sipsess.h
Adding a redirect handler allows libre to push information into baresip
about an ongoing redirection resulting from a 3xx code.
> SIP redirect callbackfunction

- .github/workflows/clang-analyze.yml
- src/http/client.c
- src/http/request.c
- src/httpauth/digest.c
- src/jbuf/jbuf.c
- http/request.c:send_req - Dead assignment
- http/client.c:read_file - Dead assignment
- http/client.c:http_request - Dead assignment
- jbuf/jbuf.c:calc_bufftime - Dead initialization
- httpauth/digest.c:httpauth_digest_make_response - Dereference of null pointer
> fix clang analyze warnings

- include/re_fmt.h
- src/fmt/prm.c
This e.g. would allow to specify in baresip account specific parameters in the `extra` address parameter.
e.g.:
```
<sip:user@domain.com;transport=tcp>;auth_pass=secret;extra=ex1=1,ex2=2,ex3=3;medianat=ice
```
Can be used for baresip-apps PR: https://github.com/baresip/baresip-apps/pull/5
> fmt: support different separators for parameter parsing

- src/sip/transp.c
This PR fixes baresip/baresip#1487
> add essential fields check

- src/sa/sa.c
On some old systems getaddrinfo() is not available.
> sa: fix build for old systems

- src/sa/sa.c
Fixes #124 
Since `hints.ai_family` is specified as `AF_UNSPEC` we can drop `AI_V4MAPPED`
> sa/addrinfo: fix openbsd (drop AI_V4MAPPED flag)

- src/sip/transp.c
In order to use an IPv6 link local address as destination address
for UDP/TCP packets, the sin6_scope_id needs to be set to the used network
interface.
This PR adds the support for IPv6 link local addresses for sip and http.
SIP calls to IPv6 link local addresses and answering calls from IPv6 link local remote will be possible.
> IPv6 link local support

- src/sip/transp.c
A transport object where the laddr matches the address found by net_dst_source_addr_get() will be preferred.
But if not found the fallback transport is returned. This guaranties the old behavior if not all laddrs are added by baresip.
> sip: add fallback transport for transp_find()

- include/re_sip.h
- src/sip/request.c
- src/sip/sip.c
- src/sip/sip.h
- src/sip/transp.c
Currently always UDP is used if no "transport=" parameter is present.
This PR allows to set a different default transport protocol.
> SIP default protocol

- mk/re.mk
- src/tls/openssl/tls.c
* THIS IS ONLY FOR DEBUGGING PURPOSE.
* The key logger is only available with OpenSSL >= v1.1.1
* It is only compiled if TRACE_SSL is defined
* TRACE_SSL must define a writeable location and filename
* In case the conditions above are fulfiled, it
allows the developer to log key material of a tls connection.
Including the key material into eg. Wireshark allows the developer
to decrypt the SSL stream.
> tls: add keylogger callback function

- include/re_http.h
- src/http/request.c
http authorization always uses Bearer as token type.
Api was added to support custom token types.
> http/client: support other auth token types besides bearer

- src/tls/openssl/tls_tcp.c
* SSL_use_certificate_chain_file does not always replace existing
certificates in the SSL objects cert storage.
* To force the usage of the client cert, the cert store of the
SSL object is now cleared befor a new certificate is loaded
> tls: fix client certificate replacement

- src/http/client.c
http modul currently does not resolve ipv6 dns entries.
This PR uses ipv6 dns entries, if no ipv4 address was found.
> http/client: support dns ipv6

- src/jbuf/jbuf.c
- src/sdp/msg.c
jbuf.c:193  High  V595  The 'ft' pointer was utilized before it was verified against nullptr. Check lines: 193, 194.
msg.c:473  High  V595  The 'sess' pointer was utilized before it was verified against nullptr. Check lines: 473, 479.
> fix warnings from PVS-Studio C++ static analyzer

- src/json/decode.c
Fix parsing simple json containing only 1 value without a name
.e.g. '"HelloWorld"' or '42'
> json: fix parsing json containing only single value

- src/dns/client.c
Return error only if IPv4 and IPv6 udp_listen fail.
If IPv6 is completely disabled with kernel line "ipv6.disable=1", dnsc_alloc fails with HAVE_INET6=1 enabled.
> dns: fix dnsc_alloc with IPv6 disabled

- include/re_sip.h
- include/re_sipsess.h
- src/sip/request.c
- src/sipevent/notify.c
- src/sipevent/subscribe.c
- src/sipreg/reg.c
- src/sipsess/accept.c
- src/sipsess/ack.c
- src/sipsess/connect.c
- src/sipsess/modify.c
- src/sipsess/sess.c
- src/sipsess/sipsess.h
`sipsess_connect()` uses a function pointer `sipsess_desc_h` to retrieve the session description (e.g. SDP) instead of the pre-encoded buffer `desc`.
Encoding of the session description still does the application (e.g. baresip still encodes SDP).
> set sdp laddr to SIP src address

- src/sdp/msg.c
This patch adds support for the SDP offer to include all available
local media formats regardless of the already selected format.
It allows the practical usecase of a re-Invite as late offer. The
receiver of the re-Invite can include a list of all available
media formats as SDP offer.
> sdp: include all media formats in SDP offer

- src/sipsess/sess.c
This fixes a segfault that occurs when the session is terminated abnormally.
@juha-h Please could you test with your setup where baresip is restarted while an INVITE is about to be sent?
> sipsess: do not call desc handler on shutdown

- src/http/client.c
The brackets `[1111:2222::3333]` had been missing.
> http: HTTP Host header conform to RFC for IPv6 addresses

- mk/re.mk
- src/dns/mod.mk
If apps are build static, not all necessary LFLAGS are included for macOS:
```shell
make -C re libre.a
make -C rem librem.a
make -C baresip STATIC=1 MODULES=
./baresip
dyld[838]: symbol not found in flat namespace '___CFConstantStringClassReference'
[1]    838 abort      ./baresip
```
(Baresip builds/runs fine with some modules, because some are including the necessary frameworks).
> mk: move darwin dns LFLAGS to re.mk (fixes static builds)

- Makefile
Inspired by https://github.com/baresip/baresip/pull/87 to make it easier to see what's being done really during build, if make run with `V=1`.
This is especially important since we do some tricky run-time checks for some components and the only way to find-out
what was detected and what not is to see full set of definitions passed in `CFLAGS`.
> build infrastructure: silent and verbose modes

- mk/re.mk
> mk: use posix regex for sed gcc major version detection

- src/dns/ns.c
man resolv.conf (OpenBSD)
> A hash mark (#) or semicolon (;) in the file indicates the beginning of a comment;
> subsequent characters up to the endof the line are not interpreted by the routines that read the file.
Fixes #187
> dns: fix parse_resolv_conf for OpenBSD

- src/md5/wrap.c
refs #197 
Fixes:
```
src/md5/wrap.c:29:8: warning: 'MD5' is deprecated [-Wdeprecated-declarations]
(void)MD5(d, n, md);
^
.././include/openssl/md5.h:52:1: note: 'MD5' has been explicitly marked deprecated here
OSSL_DEPRECATEDIN_3_0 unsigned char *MD5(const unsigned char *d, size_t n,
^
.././include/openssl/macros.h:182:49: note: expanded from macro 'OSSL_DEPRECATEDIN_3_0'
^
.././include/openssl/macros.h:62:52: note: expanded from macro 'OSSL_DEPRECATED'
^
1 warning generated.
```
> md5: use EVP_Digest for newer openssl versions

- include/re_sha.h
- src/hmac/hmac_sha1.c
- src/sha/mod.mk
- src/sha/sha.h
- src/sha/sha1.c
- src/sha/wrap.c
- src/websock/websock.c
refs #197 
fixes deprecation warnings:
```c
src/websock/websock.c:374:2: warning: 'SHA1_Init' is deprecated [-Wdeprecated-declarations] 
SHA1_Init(&ctx);                                                                                                                                                               
^                                                                                  
.././include/openssl/sha.h:49:1: note: 'SHA1_Init' has been explicitly marked deprecated here
OSSL_DEPRECATEDIN_3_0 int SHA1_Init(SHA_CTX *c);                                                                                                                                       
^ …
```
> sha: add new sha1() api

- .github/workflows/build.yml
- src/tls/openssl/tls.c
closes #197 
Fixes:
```c
src/tls/openssl/tls.c:512:10: warning: 'EC_KEY_new_by_curve_name' is deprecated [-Wdeprecated-declarations]                                                                 
eckey = EC_KEY_new_by_curve_name(eccgrp);                                                                                                                           
^                                                                                                                                                           
.././include/openssl/ec.h:996:1: note: 'EC_KEY_new_by_curve_name' has been explicitly marked deprecated here                                                                
OSSL_DEPRECATEDIN_3_0 EC_KEY *EC_KEY_new_by_curve_name(int nid); …
```
> OpenSSL 3.0

- include/re_list.h
- src/list/list.c
This adds a function that inserts elements sorted. The sort order is defined by a given `list_sort_h`.
The list sort handler seems to be always a less-equal handler. I found notes like this in rem and retest.
```
/* NOTE: important to use less than OR equal to, otherwise
the list_sort function may be stuck in a loop */
```
Should we change doxygen in re_list.h? To something like:
```
* Defines a less-equal handler to define the order of elements for the sort algorithm
```
> aubuf insert auframes sorted

- src/dns/client.c
- src/http/client.c
- src/sa/sa.c
> dns,http,sa: fix HAVE_INET6 off warnings

- CMakeLists.txt
- Makefile
For libre, it is sufficient to use the API major version as ABI major version.
> make,cmake: set SOVERSION to major version

- .github/workflows/build.yml
- CMakeLists.txt
- Makefile
- mk/re.mk
> ci: add cmake build

- src/tls/openssl/tls.c
- src/tls/openssl/tls_udp.c
fixes some warnings on windows/amd64
> tls: fix win32 warnings

- CMakeLists.txt
Looks like ninja with MSVC does not like duplicate OUTPUT_NAME.
> cmake: fix MSVC ninja

- src/srtp/srtcp.c
- src/srtp/srtp.c
- src/stun/msg.c
- src/sys/fs.c
Found by coverity scan.
```
** CID 250123:  Uninitialized variables  (UNINIT)
/src/stun/msg.c: 422 in stun_msg_chk_mi()
________________________________________________________________________________________________________
*** CID 250123:  Uninitialized variables  (UNINIT)
/src/stun/msg.c: 422 in stun_msg_chk_mi()
416     	if (fp) {
417     		((struct stun_msg *)msg)->hdr.len += FP_SIZE;
418     		(void)stun_hdr_encode(msg->mb, &msg->hdr);
419     		msg->mb->pos -= STUN_HEADER_SIZE;
420     	}
421     
>>>     CID 250123:  Uninitialized variables  (UNINIT)
>>>     Using uninitialized element of array "hmac" when calling "memcmp".
422     	if (memcmp(mi->v.msg_integrity, hmac, SHA_DIGEST_LENGTH))
423     		return EBADMSG;
424     
425     	return 0;
426     }
427     
** CID 250122: …
```
> fix coverity scan warnings

- CMakeLists.txt
build error with CMake on Android:
```
Scanning dependencies of target re-shared
[ 99%] Linking C shared library libre.so
src/net/net.c:184: error: undefined reference to 'net_rt_list'
src/net/rt.c:77: error: undefined reference to 'net_rt_list'
src/net/rt.c:142: error: undefined reference to 'net_rt_list'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [CMakeFiles/re-shared.dir/build.make:452: libre.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:99: CMakeFiles/re-shared.dir/all] Error 2
make: *** [Makefile:103: all] Error 2
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```
invoked like this:
```
+ cmake -DCMAKE_TOOLCHAIN_FILE=/usr/lib/android-ndk/build/cmake/android.toolchain.cmake -DANDROID_ABI=armeabi-v7a …
```
> cmake: fixes for Android

- src/sip/transp.c
transp.c:225:15: warning: logical not is only applied to the left hand side of
comparison [-Wlogical-not-parentheses]
This should solve the warning. I have no gcc-6 for testing. With gcc-5, gcc-7
and newer the warning is not printed.
> sip: fix gcc 6.3.0 warning for logical expression (#256)

- include/re_rtp.h
- src/rtp/fb.c
- src/rtp/pkt.c
- src/rtp/rtcp.h
as described in
https://datatracker.ietf.org/doc/html/draft-holmer-rmcat-transport-wide-cc-extensions-01#section-3.1
Note that the draft is unclear or not matching the implementation in
libwebrtc in some cases.
The libre change extends the FCI union at a low level without parsing the
packet feedback and receive deltas which will be interpreted at
application level.
> add transport-cc rtcp feedback support

- src/tls/openssl/tls.c
```
*** CID 350669:  Possible Control flow issues  (DEADCODE)
/src/tls/openssl/tls.c: 656 in tls_set_selfsigned_rsa()
650     #ifndef OPENSSL_VERSION_MAJOR
651     	if (rsa)
652     		RSA_free(rsa);
653     #endif
654     
655     	if (bn)
>>>     CID 350669:  Possible Control flow issues  (DEADCODE)
>>>     Execution cannot reach this statement: "BN_free(bn);".
656     		BN_free(bn);
657     
658     	if (err)
659     		ERR_clear_error();
660     
661     	return err;
```
> tls: fix coverity defect

- include/re_udp.h
- src/rtp/rtp.c
- src/udp/udp.c
```
** CID 350672:    (TAINTED_SCALAR)
________________________________________________________________________________________________________
*** CID 350672:    (TAINTED_SCALAR)
/src/udp/udp.c: 1017 in udp_flush()
1011     	while (-1 != us->fd  &&
1012     	       recvfrom(us->fd,  buf, SIZ_CAST sz, 0, NULL, 0) > 0);
1013     
1014     	while (-1 != us->fd6 &&
1015     	       recvfrom(us->fd6, buf, SIZ_CAST sz, 0, NULL, 0) > 0);
1016     
>>>     CID 350672:    (TAINTED_SCALAR)
>>>     Passing tainted expression "*buf" to "mem_deref", which uses it as an offset.
1017     	mem_deref(buf);
1018     	return 0;
/src/udp/udp.c: 1017 in udp_flush()
1011     	while (-1 != us->fd  &&
1012     	       recvfrom(us->fd,  buf, SIZ_CAST sz, 0, NULL, 0) > 0);
1013     
1014     	while (-1 != us->fd6 …
```
> udp: fix coverity defect

- src/json/decode.c
Since the pointer was directly decremented, the operation was normaly safe.
But setting the pointer not to a out-of-bound index should be safer for
future changes.
ref: https://sonarcloud.io/project/issues?issues=AX9vBNAyYH-a2i9ountj&open=AX9vBNAyYH-a2i9ountj&id=baresip_re
> json/decode: fix possible out of bound access, if code changes

- .github/workflows/centos7.yml
- README.md
- include/re.h
- include/re_convert.h
- src/shim/shim.c
Try to convert safely from one type (src) into another (dest). Types are auto detected.
> Add try_into conversion helper and drop gcc 4.8 support

- CMakeLists.txt
- mk/re.mk
As title, Detail please see issue #289
> fix build error on openbsd arm64 (raspberry pi)

- include/re_types.h
- src/sa/sa.c
On success, inet_ntop() returns a non-null pointer to dst.  NULL is
returned if there was an error, with errno set to indicate the error.
> sa/sa_ntop: check inet_ntop() return value

- include/re_sha.h
Fixes [restund](https://github.com/wireapp/restund) compilation (was broken since new sha wrapper)
```c
modules/zrest/zrest.c: In Function »generate_password«:                                                                                                     
modules/zrest/zrest.c:67:24: Error: »SHA512_DIGEST_LENGTH
```
> sha: add sha 256 and 512 digest length OpenSSL compats

- src/sa/sa.c
Proposal for discussion. Should we check the full IPv4 loopback range?
```bash
ip addr add 127.0.0.2/8 dev lo
```
Is currently recognized as valid address within baresip network detection:
```
--- Network debug ---
enabled interfaces:
lo:  127.0.0.2
wlp4s0:  ...
wlp4s0: ...
```
This restund fork uses a similiar workaround:
https://github.com/wireapp/restund/commit/87ca8fcf490cf1094c9107094db7c8f2e62d13ed
Will fix the failed retest if we agree (fixed now: https://github.com/baresip/retest/pull/55)
> sa/sa_is_loopback: check full IPv4 loopback range (127.0.0.0/8)

- .github/workflows/mingw.yml
this is a proposal to upgrade to openssl 3.0.2 used for the build scripts.
> workflow: upgrade to openssl 3.0.2

- include/re_net.h
- include/re_types.h
- include/re_udp.h
- src/sa/sa.c
- src/udp/udp.c
The socket handling (especially the error handling) is a bit different on win32 (see https://github.com/baresip/re/wiki/Socket-Handling).
This PR also removes unused `udp_sock_fd()` to keep fd hidden from API.
> Improve WIN32 UDP socket handling

- src/fmt/pl.c
fixes "-fsanitize=undefined"
src/fmt/pl.c:94:15: runtime error: negation of 2147483648 cannot be
represented in type 'int32_t' (aka 'int'); cast to an unsigned type to
negate this value to itself
> fmt/pl: use unsigned type before negation

- include/re_list.h
- src/list/list.c
Append means putting to tail. When the loop for the sorted insert is started
at the tail, then for a rising sequence we need only one check with a "less"
operator to know that the element has to be appended to the list.
Like `list_sort()` also `list_insert_sorted()` takes a less-equal operator.
Because we don't want to change this API detail, we declare an internal
function `le_less` by means of the given less-equal operator.
> list: O(1) sorted insert if we expect append in most cases

- CMakeLists.txt
- Makefile
- include/re.h
- include/re_pcp.h
- src/pcp/README
- src/pcp/mod.mk
- src/pcp/msg.c
- src/pcp/option.c
- src/pcp/payload.c
- src/pcp/pcp.c
- src/pcp/pcp.h
- src/pcp/reply.c
- src/pcp/request.c
Add support for PCP Port Control Protocol.
The code has been moved from librew to here.
Also added new testcases in retest.
Reference: https://en.wikipedia.org/wiki/Port_Control_Protocol
> add pcp protocol

- CMakeLists.txt
Build type can be set using:
```
$ cmake -DCMAKE_BUILD_TYPE=Release
```
Possible values are empty, Debug, Release, RelWithDebInfo and MinSizeRel
> cmake: define RELEASE for release builds

- include/re_mem.h
- src/mem/mem.c
/memstat
Memory status: (152 bytes overhead pr block)
Cur:  252 blocks, 95294 bytes (total 133598 bytes)
Peak: 252 blocks, 95446 bytes (total 133750 bytes)
Total 252 blocks allocated
> mem: remove low/high block size stats

- include/re_sip.h
- src/sip/request.c
- src/sip/sip.c
- src/sip/sip.h
- src/sip/transp.c
- src/sipevent/notify.c
- src/sipevent/subscribe.c
- src/sipreg/reg.c
- src/sipsess/ack.c
- src/sipsess/connect.c
- src/sipsess/modify.c
- sipreg: use optional TCP src port for Contact port
- sip: use local TCP port also for Via header
- sip: set TCP src port in Via and Contact also for first REGISTER
- sip: set TCP src port at laddr in all Via and Contact headers
An SBC (Session Border Controller) may block SIP requests where the Via/Contact
header port does not match the configured TCP port. The change only affects
transport TCP and TLS.
> set TCP source port in Via and Contact header

- include/re_sys.h
- src/main/init.c
- src/sys/rand.c
this is a proposal
when openssl or arc4random is used as random function, the rand_init function is obsolete.
proposal is to automatically check this instead, and init rand the first time rand is called.
the advantage is that you are not required to call `rand_init` before rand functions can be used.
> rand: init only needed for libc rand

- src/mem/mem.c
it turns out that InitOnceExecuteOnce crashes if the address of g_memlock
is sent as the 4th parameter.
in order to avoid this, refer directly to g_memlock in the initonce callback handler.
Please review and test on Windows.
> mem: init g_memLock directly

- .github/workflows/centos7.yml
- .github/workflows/fedora.yml
centos has been abandoned by RedHat I am wondering if we should support it anymore:
https://en.wikipedia.org/wiki/CentOS
I am wondering if we should support only recent versions of OpenSSL,
i.e. the same as is supported by openssl.org
CentOS 7 is using OpenSSL 1.0.2 which is not supported anymore.
Proposal for support:
* OpenSSL 1.1.1
* OpenSSL 3.0.0
* LibreSSL (from recent OpenBSD release)
Perhaps we should switch to a different RedHat based distro,
such as Fedora or RockyLinux ?
This PR switches the container from centos to fedora. Looks like it is working, but
it needs to be verified.
This is a proposal, feel free to discuss :)
> ci: test centos -> fedora

- src/main/openssl.c
https://linux.die.net/man/3/crypto_set_id_callback
> main: remove usage of crypto_set_id_callback()

- src/jbuf/jbuf.c
Replaces the out of order fault count by an expected sequence number difference
of out of order packets. The buffer has to be large enough to insert expected
out of order packets.
This PR changes only the adaptive mode. For the fixed mode `jb->wish` stays at `jb->min`.
> jbuf: improve adaptive mode

- CMakeLists.txt
- include/re_thread.h
- src/thread/mod.mk
This way HAVE_PTHREAD does not need to be defined and can be deprecated (was mostly used for WIN32 exceptions).
Ref #353
> thread: use pthread as default fallback

- src/main/init.c
- src/main/main.h
- src/main/openssl.c
Since we removed OpenSSL < 1.1.0 support, we can cleanup.
> main/openssl: cleanup

- mk/Doxyfile
- src/sa/sa.c
- src/sipsess/sess.c
- src/stun/keepalive.c
- src/tls/openssl/tls.c
this patch fixes some doxygen comments.
```
alfredh@debian:~/git/re$ make dox
warning: Tag 'COLS_IN_ALPHA_INDEX' at line 118 of file '../re-dox/Doxyfile' has become obsolete.
To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: Tag 'PERL_PATH' at line 207 of file '../re-dox/Doxyfile' has become obsolete.
To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: argument 'a4wide' for option PAPER_TYPE is not a valid enum value
Using the default: a4!
/home/alfredh/git/re/src/trice/candpair.c:141: warning: parameters of member trice_candpair_prio_order are not (all) documented
/home/alfredh/git/re/src/trice/chklist.c:158: warning: parameters of member …
```
> doxygen: update comments

- src/tls/openssl/tls_tcp.c
print the OpenSSL error queue on errors:
example:
```
tls: accept error: (r=-1, ssl_err=1)
tls: C03DC70E01000000:error:0A000416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:ssl/record/rec_layer_s3.c:1584:SSL alert number 46
tls: accept error: (r=-1, ssl_err=1)
tls: C03DC70E01000000:error:0A000416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:ssl/record/rec_layer_s3.c:1584:SSL alert number 46
```
> tls: print openssl error queue if accept failed

- include/re_dns.h
- src/dns/client.c
If `dnsc_query` is used on a server its possible to add a local dns resolver for caching (like unbound). But on desktop or mobile  this is not always possible. Some nameservers/resolvers (e.g. cheap routers) can't handle many dns requests. This PR introduces a query caching (takes into account the lowest resource record TTL).
> dns: add query cache

- src/av1/pkt.c
```
Y: MUST be set to 1 if the last OBU element is an OBU fragment that will continue in the next packet, and MUST be set to 0 otherwise.
```
https://aomediacodec.github.io/av1-rtp-spec/#44-av1-aggregation-header
> av1: change start flag to continuation flag (inverse)

- include/re_tmr.h
- src/tmr/tmr.c
```
Timers (7):
0x55ed532a83f0: th=0x55ed5112b300 expire=250ms file=modules/stdio/stdio.c:89
0x55ed533f9838: th=0x55ed51140480 expire=20199ms file=src/sipreg/reg.c:263
0x55ed511d5b68: th=0x55ed511278c0 expire=57578ms file=modules/netroam/netroam.c:206
0x55ed533a14d0: th=0x55ed5115bd90 expire=119579ms file=src/dns/client.c:350
0x55ed533850d0: th=0x55ed5115bd90 expire=119676ms file=src/dns/client.c:350
0x55ed53371710: th=0x55ed5115bd90 expire=297676ms file=src/dns/client.c:350
0x55ed534e1ef0: th=0x55ed5113bcb0 expire=897699ms file=src/sip/transp.c:526
```
> tmr: add tmr_start_dbg

- src/tls/openssl/tls.c
Red Hat Enterprise Linux 9 does not support SHA-1 (by default) in digital signatures and certificates, see also their "security hardening" document: https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html/security_hardening/using-the-system-wide-cryptographic-policies_security-hardening
Without this change, baresip's `./selftest` fails with "dtls_srtp: failed to self-sign certificate (Cannot allocate memory)" on both, CentOS Stream 9 and Red Hat Enterprise Linux 9. Fedora will likely inherit this behaviour: https://fedoraproject.org/wiki/Changes/StrongCryptoSettings3Forewarning1
For me this pull request fixes https://github.com/baresip/baresip/issues/1869
> tls: Switch from EVP_sha1() to EVP_sha256() when using it for X509_sign()

- src/http/client.c
I'm not seeing a out of bound write here, but maybe sonarcloud is smarter than me ;-) mem_zalloc should do the same trick.
https://sonarcloud.io/project/issues?resolved=false&types=BUG&id=baresip_re&open=AYEfQMmCkjI3J5RdCqEz
> http/client: use mem_zalloc in read_file

- include/re_tls.h
- src/tls/openssl/tls.c
only TLS_method() and DTLS_method() should be used now
> tls: deprecate old version specific tls methods

- include/re_rtp.h
used by all video decoders, move to a common place
> rtp: add function to calc sequence number diff

- include/re_jbuf.h
- src/jbuf/jbuf.c
Draining jitter buffer is useful when the inbound RTP stream is closed, and the application wishes to process buffered packets (e.g. to assemble the last received video frame).
> jbuf: Add drain method

- include/re_fmt.h
- src/fmt/time.c
Adds a print function for timestamps to module `fmt`.
> uag: add timestamps to SIP trace

- src/main/init.c
- src/main/main.c
Fixes #403
`re_global` is now created by `libre_init` (first `re_thread_init`) and deleted with `libre_close` and leaves a clean state (no leaking re_global pointer). This breaks `tmr_debug`  (shows nothing) if called after `libre_close`.  
These changes are needed on application side:
```c
/* check for open timers */
tmr_debug();
libre_close();
/* check for memory leaks */
mem_debug();
```
Also `fd_setsize` is affected if called before `libre_init`, new order:
```c
libre_init();
fd_setsize(-1);
```
I think leaving libre in a clean state after `libre_close` is worth it. I added sanity checks and warnings (like `fd_setsize: re not ready`) for applications.
> main: refactor libre_init and re_global handling

- include/re_main.h
- src/main/main.c
This commit allows to create an event loop context and keep a reference to it in the caller application. After that, this and other threads are allowed to attach to and detach from this context as needed. Threads are synchronized by calling `re_thread_enter`/`leave`. The re context can be destroyed by calling `mem_deref`.
This is useful to allow threads that are not running event loop to invoke methods on an event loop context that is created and managed by another thread.
> main: Add support for external threads attaching/detaching re context

- CHANGELOG.md
- CMakeLists.txt
- Makefile
- debian/changelog
- `CMakefile`
- `Makefile`
- `debian/changelog`
- Press `Auto-generate Release notes` 
- `CMakefile` (Bump PROJECT_SOVERSION)
- `Makefile` (Bump ABI_MAJOR)
- libre
- librem
- retest (needs only a version tag - no PR)
- baresip
- Maybe `Auto-generate Release notes` is needed to update (delete last notes first)
> release v2.5.0

- include/re_atomic.h
I replaced __GNUC_PREREQ macro to its definition but everything else is the same
> Fix compilation error on musl: __GNUC_PREREQ macro defined only for libc library

- CMakeLists.txt
- README.md
- include/re_sip.h
- include/re_sipsess.h
- src/sip/mod.mk
- src/sip/msg.c
- src/sip/rack.c
- src/sipsess/accept.c
- src/sipsess/connect.c
- src/sipsess/listen.c
- src/sipsess/mod.mk
- src/sipsess/prack.c
- src/sipsess/reply.c
- src/sipsess/sipsess.h
This PR adds support for [RFC 3262](https://datatracker.ietf.org/doc/html/rfc3262) which enables provisional SIP responses to be sent reliably by acknowledging them through PRACKs.
Related:
- https://github.com/baresip/baresip/pull/1930
- https://github.com/baresip/retest/pull/88
> sip: add RFC 3262 support

- include/re_bfcp.h
- src/bfcp/bfcp.h
- src/bfcp/conn.c
This includes both receiving inbound connections and initiating outgoing connections.
Note: This is somewhat different from our internal patch to support TCP for BFCP, so it is not fully tested. Our internal patch relies on other changes that were not included in this patch. Sending and receiving BFCP messages over TCP is tested.
> bfcp: Add support for TCP transport for BFCP

- src/sip/strans.c
- src/sipsess/accept.c
- src/sipsess/reply.c
This PR fixes an issue introduced with PR #419. It prevented a call from being canceled during early media/ringing if a 100rel/PRACK exchange happened in the transaction.
~~Without the changes in `src/sipsess/accept.c`, the SIP 4xx responses were being retransmitted until T2 fired even though the 4xx responses were being ACKed. I haven't been able to figure out why that happened, maybe there is a better solution than the one I propose in this PR.~~
Update: The server transactions are now being correctly used. The changes in this PR provide a clean solution.
> strans/accept: fix cancel/rejection

- include/re_hash.h
- src/hash/hash.c
Useful for manual hash list iteration.
> hash: add hash_list_idx()

- include/re_tls.h
- src/tls/openssl/tls.c
- Add a method to set OpenSSL TLS certificate. This allows an application to provide its own TLS certificate in the form of OpenSSL structures to use in a TLS context.
- Avoid using OpenSSL internal type names. OpenSSL documentation only mentions `SSL_CTX` as the TLS context type, so use that consistently in libre function definitions.
> tls: Add a method to set OpenSSL certificate

- src/sipsess/connect.c
- src/sipsess/listen.c
- src/sipsess/reply.c
- src/sipsess/sipsess.h
[According to RFC 3262](https://datatracker.ietf.org/doc/html/rfc3262#section-5), PRACKs and reliable 1xx responses can contain both SDP answers and offers. E.g. if a reliable 1xx response contains an offer, the PRACK **MUST** contain an answer. This behavior is now correctly supported.
This situation can occur when an initial INVITE did not contain SDP, but the 1xx response did (which is rare in most real world scenarios).
> sipsess: fix PRACK offer/answer behavior

- include/re_thread.h
- src/jbuf/jbuf.c
- src/main/main.c
- src/rtp/sess.c
- src/thread/posix.c
- src/thread/thread.c
- src/thread/win32.c
- src/trace/trace.c
This PR cleanups return value handling for some C11 thread functions.
It renames `mtx_alloc` -> `mutex_alloc` and `thrd_create_name` -> `thread_create_name` to make clear that these are libre related functions that uses other return values (0 for success etc.).
Fixes #429
> thread: thrd_error fixes

- src/sipsess/accept.c
- src/sipsess/connect.c
remove unneccessary null check and remove dead code part that is covered by sipsess_reply_xx functions.
fixes #432
> sipsess: fix coverity warnings

- README.md
- src/sipsess/listen.c
- src/sipsess/modify.c
- src/sipsess/reply.c
- src/sipsess/sipsess.h
This PR adds support for [RFC 3311](https://datatracker.ietf.org/doc/html/rfc3311) - the SIP UPDATE method.
Related:
- https://github.com/baresip/baresip/pull/1941
> sip: add RFC 3311 support

- src/rtmp/amf_dec.c
reported by Coverity:
```
** CID 354662:  Insecure data handling  (TAINTED_SCALAR)
/src/rtmp/amf_dec.c: 175 in amf_decode_value()
________________________________________________________________________________________________________
*** CID 354662:  Insecure data handling  (TAINTED_SCALAR)
/src/rtmp/amf_dec.c: 175 in amf_decode_value()
169     			return EPROTO;
170
171     		err = odict_alloc(&object, 32);
172     		if (err)
173     			return err;
174
>>>     CID 354662:  Insecure data handling  (TAINTED_SCALAR)
>>>     Using tainted variable "array_len" as a loop boundary.
175     		for (i=0; i<array_len; i++) {
176
177     			char ix[32];
178
179     			re_snprintf(ix, sizeof(ix), "%u", i);
180
```
> rtmp: check upper bound for amf array

- src/mem/mem.c
Ensure that the pointer returned by `mem_alloc` & co. is properly aligned similar to `malloc` on a given platform. This is important e.g. for SIMD processing, including libc string operations.
Also, made `mem_realloc` optimize away `realloc` call if there is enough storage in the allocated buffer. This only works if the input pointer is the only reference to the memory block.
Also, fixed formatting in `mem_status`.
> mem: Align data to natural alignment

- src/net/linux/rt.c
before:
```
net routes:
Destination                                 Next Hop                                 Iface           Type
0.0.0.0/0                                   10.0.1.1                                 eno1            
10.0.1.0/24                                 ?                                        eno1            
::1/128                                     ?                                        lo              
fe80::/64                                   ?                                        eno1             LINKLOCAL
```
after:
```
net routes:
Destination                                 Next Hop                                 Iface           Type
0.0.0.0/0                                   10.0.1.1                                 eno1            
10.0.1.0/24 …
```
> net: linux/rt: init gw to correct af

- include/re_rtp.h
This allows the user to send RTCP packets that are not (yet) supported by libre.
> rtp: Add `rtcp_send` declaration to the public header

- CMakeLists.txt
- include/re_atomic.h
- src/main/main.c
- src/mem/mem.c
This allows to use mem API for shared memory objects from multiple threads.
> mem: Make nrefs atomic

- include/re_atomic.h
- src/main/main.c
- src/mem/mem.c
Adding some shortcuts like `re_atomic_weak` makes code more readable.
Full version:
```c
while (re_atomic_load(&run, re_memory_order_relaxed)) {
```
Shortcut:
```c
while (re_atomic_weak(&run)) {
```
> atomic: add some short atomic alias helpers

- include/re_atomic.h
- src/main/main.c
- src/mem/mem.c
The `_weak` and `_strong` suffixes are misleading/confusing compared to `atomic_compare_exchange_strong`...
- re_atomic_rlx (relaxed)
- re_atomic_acq (acquire)
- re_atomic_rls_set (release)
- re_atomic_seq (sequentially-consistent)
Are more meaningful, less confusing and explicit.
> atomic: rename helpers

- CMakeLists.txt
- mk/re.mk
Atomic operations should always be explicit.
- C11 default is sequentially-consistent memory ordering (performance overhead on some systems like ARM)
- Some expressions like `x = x + 1` (atomic read followed by atomic write), are not atomic (easy to make mistakes)
- C99 and MVSC has to be explicit
> cmake,make: add clang atomic-implicit-seq-cst warning

- CMakeLists.txt
* ordered includes alphabetically
* added missing includes re_pcp.h and re_thread.h
> cmake: add missing includes to install

- src/sipsess/prack.c
If a UA receives a response to a PRACK after the session has terminated, don't call the prack handler.
Fixes https://github.com/baresip/baresip/issues/1996.
> Fix prack handling

- include/re_mem.h
- src/mem/secure.c
- src/tls/openssl/tls.c
This ensures that sensitive data is not left on the stack.
> tls: Securely clear memory from private key material

- include/re_atomic.h
This adds support for older gcc versions that didn't support __atomic intrinsics.
Related to https://github.com/baresip/re/pull/446#issuecomment-1204383834
CC @cspiel1
> atomic: Add support for gcc __sync intrinsics

- include/re_btrace.h
- src/btrace/btrace.c
Fixes gcc warnings
```
warning: declaration of 'btrace' shadows a global declaration
```
> btrace: fix gcc 4.3.5 warnings

- include/re_dns.h
- src/dns/client.c
Benefits:
- considers `/etc/hosts` entries
- maybe works better on restricted systems
> dns/client: add async getaddrinfo usage

- include/re_async.h
- src/async/async.c
This way fd_poll can unblocked immediately, without extra dummy handlers.
> async: make work handler and callback optional

- include/re_base64.h
- src/base64/b64.c
Useful for OAUTH PKCE https://www.rfc-editor.org/rfc/rfc7636.html#appendix-A
Ref: [RFC 4648 section 5](https://www.rfc-editor.org/rfc/rfc4648.html#section-5)
> base64: Encoding/Decoding with URL and Filename Safe Alphabet

- CMakeLists.txt
- cmake/re-config.cmake
- cmake/re.cmake
This way we can share/maintain options with other projects (like we did with re.mk).
> cmake: move definitions to re-config.cmake

- src/tcp/tcp.c
When I compile libre using `arm-linux-musleabi-gcc` cross-compiler with musl library I encountered a compilation issue:
```
[ 59%] Building C object CMakeFiles/re-objs.dir/src/tcp/tcp.c.o
.../git/re/src/tcp/tcp.c: In function ‘tcp_sock_bind’:
.../git/re/src/tcp/tcp.c:725:12: error: ‘NI_MAXSERV’ undeclared (first use in this function)
char serv[NI_MAXSERV] = "0";
^~~~~~~~~~
.../git/re/src/tcp/tcp.c:725:12: note: each undeclared identifier is reported only once for each function it appears in
.../git/re/src/tcp/tcp.c:725:7: warning: unused variable ‘serv’ [-Wunused-variable]
char serv[NI_MAXSERV] = "0";
^~~~
.../re/src/tcp/tcp.c: In function ‘tcp_conn_alloc’:
.../re/src/tcp/tcp.c:886:12: error: ‘NI_MAXSERV’ undeclared (first use in this function)
char serv[NI_MAXSERV] = "0";
^~~~~~~~~~ …
```
> Fix error: ‘NI_MAXSERV’ undeclared

- src/net/ifaddrs.c
- src/net/posix/pif.c
When I compile libre using arm-linux-musleabi-gcc cross-compiler with musl library I encountered a compilation issue:
```
/tmp/re/src/net/posix/pif.c: In function ‘net_if_getaddr4’:
/tmp/re/src/net/posix/pif.c:65:16: error: storage size of ‘ifrr’ isn’t known
struct ifreq ifrr;
^~~~
/tmp/re/src/net/posix/pif.c:65:16: warning: unused variable ‘ifrr’ [-Wunused-variable]
/tmp/re/src/net/posix/pif.c: In function ‘net_if_list’:
/tmp/re/src/net/posix/pif.c:104:15: error: array type has incomplete element type ‘struct ifreq’
struct ifreq ifrv[32], *ifr;
^~~~
/tmp/re/src/net/posix/pif.c:105:16: error: storage size of ‘ifc’ isn’t known
struct ifconf ifc;
^~~
/tmp/re/src/net/posix/pif.c:126:7: error: increment of pointer to an incomplete type ‘struct ifreq’
++ifr) {
^~ …
```
> Fix error: storage size of ‘ifrr’ isn’t known

- src/sdp/media.c
Before this patch, when offer was received, local id of common media was changed to match that in the offer. As result, the id could conflict with some other local media id.
I don't see a need for the id change. Since this is a very serious bug, my suggestion is to the merge this PR. If someone thinks the id needs to be changed then he/she can make another PR that fixes the conflict.
After this PR, the re-INVITE test of https://github.com/baresip/baresip/issues/2073 worked fine.
> Correctly update local media format ids to match those in the offer

- debian/rules
Fixed wrong `prefix` value in `/usr/lib/pkgconfig/libre.pc`.
> debian: fix prefix

- src/http/client.c
Reported-by: Coverity Scan
New defect(s) Reported-by: Coverity Scan
Showing 1 of 1 defect(s)
```c
** CID 277673:  Null pointer dereferences  (REVERSE_INULL)
/src/http/client.c: 396 in send_req_buf()
________________________________________________________________________________________________________
*** CID 277673:  Null pointer dereferences  (REVERSE_INULL)
/src/http/client.c: 396 in send_req_buf()
390     
391     static int send_req_buf(struct conn *conn)
392     {
393     	int err;
394     	struct http_req *req = conn->req;
395     
>>>     CID 277673:  Null pointer dereferences  (REVERSE_INULL)
>>>     Null-checking "conn" suggests that it may be null, but it has already been dereferenced on all paths leading to the check.
396     	if (!conn || !req || !req->cli)
397     		return …
```
> http/client: fix possible null pointer dereference

- include/re_fmt.h
- include/re_types.h
- src/fmt/print.c
Adds `__restrict` macro for WIN32
Fixes #512
> types,fmt: use re_restrict

- include/re_sip.h
- src/sip/auth.c
Adds UAS authentication in `src/sip/auth.c`. This is needed for processing incoming out-of-dialog REFER which we propose here for baresip: https://github.com/baresip/baresip/pull/2115.
> refer out of dialog

- include/re_dns.h
- src/dns/client.c
- src/http/client.c
add api dnsc_getaddrinfo_enabled.
Use dnsc_getaddrinfo_enabled to prevent reset of getaddrinfo enabled during http_client_set_config
> dns, http: add dnsc_getaddrinfo_enabled. prevent reset of getaddrinfo enabled

- src/conf/conf.c
it looks like Coverity scan is complaining that we are not checking the number of bytes returned.
```
6. tainted_data_transitive: Call to function mbuf_write_mem with tainted argument buf transitively taints *mb->buf. [[show details](https://scan8.scan.coverity.com/eventId=12365060-8&modelId=12365060-0&fileInstanceId=62023522&filePath=%2Fsrc%2Fmbuf%2Fmbuf.c&fileStart=207&fileEnd=232)]
CID 93696 (#1 of 1): Untrusted value as argument (TAINTED_SCALAR)
11. tainted_data: Passing tainted expression *mb->buf to mbuf_write_mem, which uses it as an offset. [[show details](https://scan8.scan.coverity.com/eventId=12365060-26&modelId=12365060-1&fileInstanceId=62023522&filePath=%2Fsrc%2Fmbuf%2Fmbuf.c&fileStart=207&fileEnd=232)]
Ensure that tainted values are properly sanitized, by checking that their …
```
> conf: check if returned size is larger than buffer

- CMakeLists.txt
- include/re_crc32.h
- src/crc32/crc32.c
- src/crc32/mod.mk
- src/stun/msg.c
Add a crc32 wrapper agnostic to CRC32 backend
> crc32: add re wrapper

- src/pcp/request.c
cppcheck --version
Cppcheck 2.3
```
src/pcp/request.c:115:13: warning: Possible null pointer dereference: msg [nullPointer]
if (err || msg->hdr.result != PCP_SUCCESS ) {
^
src/pcp/request.c:141:29: note: Calling function 'completed', 3rd argument 'NULL' value is 0
completed(req, ETIMEDOUT, NULL);
^
src/pcp/request.c:115:13: note: Null pointer dereference
if (err || msg->hdr.result != PCP_SUCCESS ) {
^
```
> pcp: fix cppcheck warning

- src/fmt/print.c
```
src/fmt/print.c:77:15: error: Pointer arithmetic overflow; 'buf' buffer size is 64 [ctuPointerArith]
char c, *p = buf + NUM_SIZE - 1;
^
src/fmt/print.c:272:20: note: Calling function local_itoa, 1st argument is uninitialized
len = local_itoa(num, (sn < 0) ? -sn : sn, base,
^
src/fmt/print.c:77:15: note: Using argument buf
char c, *p = buf + NUM_SIZE - 1;
```
> fmt/print: fix cppcheck overflow warning

- include/re_telev.h
- src/telev/telev.c
Adds a function `telev_is_empty()` to query if DTMF characters have been sent out completely.
> send DTMF via hidden call

- src/sipreg/reg.c
A periodic un-REGISTER should be done only if `fbregint` (fallback SIP server
registration interval) was set.
> sipreg: avoid sending un-REGISTER periodically

- src/sipsess/update.c
UPDATEs are now sent with Contact header which is mandatory according to RFC 3311.
> sipsess/update: Add Contact header to UPDATE

- include/re_udp.h
- src/udp/udp.c
Proposal to remove this function in order to keep the API small and simple.
The function is not used by baresip or retest.
> udp: remove udp_send_anon()

- include/re_fmt.h
- src/fmt/str.c
- src/sdp/msg.c
- As per RFC 8866, without rtpmap and possibly with fmtp
- This example shows [unregistered] media type application/vnd.wireguard
- Wireshark does not like the fmtp: line -- that would be a bug there
```
v=0
o=- 3280287138 1947228850 IN IP6 2001:db8:12::34
s=-
c=IN IP6 2001:db8:12::34
t=0 0
m=application 9638 udp vnd.wireguard
a=fmtp:vnd.wireguard pubkey=z7otO6+NKCOM/I7gq6mvcVqYyX3u27Z0WVKMY/juel8=
a=sendrecv
```
> SDP support for <proto> udp

- include/re_fmt.h
- src/fmt/pl.c
relates to:
https://github.com/baresip/baresip/pull/2163
> fmt: add pl_trim functions

- include/re_tls.h
- src/tls/openssl/tls.c
- src/tls/openssl/tls.h
this one is for discussion ...
in general we should try to avoid ifdef in public header files.
The API in re_tls.h should be a generic TLS api, and should not expose any
implementation details (such as OpenSSL).
It is possible to add support for other TLS backends, such as:
- macOS tls stack
- windows tls stack
- mbed TLS
- ... etc ...
look at the CURL source code for ideas and inspiration
> tls: remove ifdef from public API

- include/re_sip.h
- src/sip/transp.c
- src/sipreg/reg.c
the parameter `struct sip_conncfg` is passed by value, which means the whole struct has to be
copied to the call-stack.
it is more efficient to pass by reference, i.e. use a pointer
> sip: sip_conncfg_set pass by reference

- include/re_dns.h
- src/dns/client.c
- src/http/client.c
Set dns timeout separately to skip hash table realloc.
http client set config should changes only idle connect timeouts also in dnsc
> dnsc get conf and skip hash alloc without hash size changes

- src/list/list.c
Fixes a segfault when iterating the list within data destructor, since head and tail are not updated.
See: https://github.com/baresip/retest/pull/151
> list: fix list_flush head and tail

- src/sipreg/reg.c
- sipreg: case-insensitive comparison of ;transport=tls
- sipreg: do not compare port numbers of Contact header
These two commits solve the problem that in some situations the `;expires=` parameter in the Contact header in the response to the REGISTER is not evaluated.
There are two more problems/questions which are related to this:
- Currently there is no error handling for the case where the `contact_handler` returns `false`. Then the expires is not evaluated, without any warning. Should there be any error handling?
- What if the SIP registrar rewrites the port number in the Contact handler. Should `re`, `baresip` update it's Contact handler for following SIP requests?
> sipreg fix contact handler `expires` evaluation

- include/re_ice.h
- src/ice/cand.c
- src/ice/ice.h
- src/ice/icem.c
RFC 5245 and 8445 defines:
> Base: The transport address that an ICE agent sends from for a particular candidate.  For host, server-reflexive, and peer- > reflexive candidates, the base is the same as the host candidate. For relayed candidates, the base is the same as the relayed candidate (i.e., the transport address used by the TURN server to send from). 
This allows also a RELAY only policy (without any other candidates), like defined with iceTransportPolicy (WebRTC).
> ice: local candidate policy config

- .github/workflows/valgrind.yml
Looks like github actions has bumped `ubuntu-latest`
> ci/valgrind: use ubuntu-20.04

- src/tls/openssl/tls.c
This fixes a segmentation fault that appear when the tls object is freed before
the SSL object and TLS session reuse was enabled.
> tls: clear session callbacks in destructor

- include/re_udp.h
- src/udp/udp.c
usecase: use udp_sock with external/custom sockets
> udp: add optional send/recv handler

- src/main/main.c
this would allow for calling `libre_init` twice and returning 0.
https://github.com/baresip/retest/pull/163
> main: allow for init twice

- CMakeLists.txt
> cmake: add check_c_compiler_flag for atomic-implicit-seq-cst warning

- CMakeLists.txt
- README.md
- cmake/re-config.cmake
- include/re.h
- include/re_sa.h
- include/re_unixsock.h
- src/sa/sa.c
- src/unixsock/unixsock.c
Usage example:
```c
struct sa srv;
re_sock_t fd;
err = sa_set_str(&srv, "unix:/run/http.sock", 0);
if (err)
return err;
err = unixsock_listen_fd(&fd, &srv);
if (err)
return err;
re_printf("listen: %j\n", &srv);
err = http_listen_fd(sock, fd, http_req_handler, mix);
```
> sa,unixsock: add unix domain socket support

- include/re_mbuf.h
- include/re_rtp.h
- src/mbuf/mbuf.c
- src/rtp/rtp.c
Needed for Video NACK handling.
> RTP Resend

- CMakeLists.txt
- include/re_tls.h
- src/tls/openssl/sni.c
- src/tls/openssl/sni.h
- src/tls/openssl/tls.c
- src/tls/openssl/tls.h
tls: support multiple TLS server certificates
Multiple certificates combined with private key and host name for the host name
verification can be added with a new function `tls_add_certf()`.
For incoming SIP requests a certificate is selected by SNI in the TLS client
hello before `SSL_accept()` is called.
e.g. use case: incoming OPTIONS from SIP servers for client is alive polling
TODO: maybe in follow up PRs in order to keep this PR small.
- cleanup/combine with
```
commit 21f36e31522b8d2106e6c1daf64ea0eba626f79c
Author: Christoph Huber <c.huber@commend.com>
Date:   Mon Apr 12 09:45:50 2021 +0200
transp: add and use different client certificates
```
- The names `tls_set_verify_server()` and  `tls_set_verify_client()` are not very proper. Maybe we could add a deprecated logging/doxygen …
> TLS server support SNI based certificate selection

- cmake/re-config.cmake
- include/re_sa.h
- src/sa/sa.c
Unix sockets are turned on per default in cmake and are used in header re_sa.h. This PR enables the unix socket flag, if not explicitly defined during builds of external libs using re_sa.h.
Edit by @cspiel1 : Relates to https://github.com/baresip/baresip/issues/2402
> cmake, sa: enable unix sockets, if HAVE_UNIXSOCK is undefined

- src/dns/client.c
It's not enough to reference `rr` for handle caching, since if the original query is derefed the `rr->le_priv->list` is derefed too. This can lead to heap-use-after-free crashes if list is accessed (like with `list_unlink`). This PR references the complete rrlv lists for caching.
Fixes https://github.com/baresip/retest/issues/168
> dns/client: fix rrlv reference cache handling

- include/re_tls.h
- src/tls/openssl/tls_udp.c
When used with WebRTC, the remote endpoint may send DTLS packets from any port. In this context we should have only one DTLS connection that is used for e.g. SRTP keying and SCTP transport.
This happens with Safari 16.1 where it sends DTLS Handshake from one port, and DTLS Alert from another port.
> dtls: add single connection mode

- include/re_types.h
1. avoid potential naming conflicts
2. add prefix to make the code more readable
> types: add RE_ prefix to ARRAY_SIZE()

- src/tcp/tcp_high.c
If `tcp_listen` is used, there is no way to specify backlog (used for example in `http_listen`). Now the default can be overriden at compile time:
```
cmake -B build -DCMAKE_C_FLAGS="-DRE_TCP_BACKLOG=128"
```
> tcp: add RE_TCP_BACKLOG

- src/mod/win32/dll.c
- src/net/win32/wif.c
- src/tls/openssl/tls.c
Fixes the warnings:
```
alfredh@debian:~/git/re$ doxygen mk/Doxyfile 
/home/alfredh/git/re/src/mod/mod_internal.h:15: warning: argument 'h' from the argument list of _mod_close has multiple @param documentation sections
/home/alfredh/git/re/src/mod/mod_internal.h:13: warning: argument 'name' from the argument list of _mod_open has multiple @param documentation sections
/home/alfredh/git/re/src/mod/mod_internal.h:14: warning: argument 'h' from the argument list of _mod_sym has multiple @param documentation sections
/home/alfredh/git/re/src/mod/mod_internal.h:14: warning: argument 'symbol' from the argument list of _mod_sym has multiple @param documentation sections
/home/alfredh/git/re/include/re_net.h:73: warning: argument 'ifh' from the argument list of net_if_list has multiple @param …
```
> Fix doxygen warnings

- src/tcp/tcp.c
Proposal to remove SO_LINGER. Should not be needed, since disabled by default.
> tcp: remove SO_LINGER socket option

- src/tcp/tcp.c
only needed after connect(2):
```
use getsockopt to read the SO_ERROR option at
level SOL_SOCKET to determine whether connect() completed
successfully (if SO_ERROR is zero).
```
> tcp: check SO_ERROR only for active connections

- src/list/list.c
Conditions within a loop can be expensive, better to put the forward decision outside the loop.
> list: improve list_apply performance

- src/sip/auth.c
ETIME is not available on OpenBSD and maybe other UNIX systems
> auth: replace ETIME with ETIMEDOUT

- src/md5/wrap.c
- src/tls/openssl/sni.c
- src/tls/openssl/tls.c
- src/tls/openssl/tls.h
- src/tls/openssl/tls_tcp.c
Solves: https://github.com/baresip/re/issues/678
> tls: remove obsolete openssl version check and fix libressl build

- include/re_main.h
- include/re_thread.h
- include/re_tmr.h
- src/main/main.c
- src/tmr/tmr.c
It's possible that a worker thread can reuse a `tmr` (for example if `turnc` recv helper is executed from a different re poll thread and stun refresh tmr is updated). The new worker thread has to unlink the old `tmr` from main thread timer list. This needs thread safe mutex handling. The impact on performance is likely to be small because the competitive situation is low.
> tmr,main: thread safe tmr handling

- include/re_hmac.h
- src/hmac/hmac_sha1.c
- test/hmac.c
Add a wrapper for HMAC-SHA256 using OpenSSL or Apple CommonCrypto as backend
> hmac: add stateless HMAC-SHA256 wrapper

- cmake/re-config.cmake
- include/re_fmt.h
- include/re_types.h
- src/fmt/str.c
- src/thread/thread.c
- test/fmt.c
- test/test.c
- test/test.h
- `Setup -> Display options -> Show custom thread names`
```bash
top -H -p <pid>
```
```bash
$ ps H -o 'tid comm' <pid>
TID COMMAND
358386 baresip
358395 baresip
358396 async worker th
358397 async worker th
358398 async worker th
358399 async worker th
```
> thread: add thread name handling

- src/jbuf/jbuf.c
For the RX thread https://github.com/baresip/baresip/discussions/2445 `jbuf_debug()` should also be thread safe.
> jbuf: allocate mutex and lock also jbuf_debug()

- src/sys/fs.c
- `r` Opens for reading. If the file doesn't exist or can't be found, the fopen_s call fails.
- `r+` Opens for both reading and writing. The file must exist.
> sys/fs: fix fs_fopen read only mode (should not create file)

- src/rtp/rtp.c
RTCP socket is unused when rtcp-mux is enabled. RTP socket is used for sending and therefore it should be checked instead.
> rtp: Don't check RTCP socket if rtcp-mux is enabled

- .github/workflows/build.yml
- .github/workflows/cmake_win.yml
- .github/workflows/coverage.yml
- .github/workflows/sanitizers.yml
- .github/workflows/valgrind.yml
- .gitignore
- CMakeLists.txt
- Makefile
- README.md
`retest` target is not needed for normal builds and should be build separate (includes automatic `re/libre` target):
```bash
cmake -B build && cmake --build build -t retest -j
```
> misc: add Makefile helpers and exclude retest from all target

- include/re_sa.h
- src/sa/sa.c
- test/sa.c
The application and library must use the same build flags when building struct sa.
If different build flags are used, random and mysterious crashes may occur.
> sa: add sa_struct_get_size() to check size

- rem/aubuf/aubuf.c
It is possible that the reader expects a different sample format then stored
in the audio buffer.
> aubuf: set sample format when frame is read

- .github/workflows/build.yml
Avoid hardcoded OpenSSL path on macOS
> ci: avoid hardcoded OpenSSL path on macOS

- rem/aubuf/aubuf.c
- test/aubuf.c
This avoids that the timestamp is overwritten with an intermediate timestamp if
the loop in read_auframe() is traversed more then once.
This lead to ugly ringtone artifacts.
> aubuf: set auframe fields correct in read_auframe loop

- include/re_list.h
- src/list/list.c
- test/list.c
`list_insert_sorted()` can handle two cases, forward and reverse sort (on already sorted list).
So I think we can reduce complexity.
> list: refactor/optimize list_insert_sorted

- include/re_tmr.h
- src/tmr/tmr.c
to allow jiffie-accurate interval timer continuation
usually called from within the handler function
RTP timing can normally be derived best from an audio source.
This does not work when delivering content from a file, or when
delivering generated content.
The `tmr_continue()` call is a slight modification of `tmr_start()`
and can be used to continue a timer after an internal, which is
added to the current timeout, avoiding stacking timing errors.
> tmr: add tmr_continue()

- include/re_atomic.h
Fixes https://github.com/baresip/re/issues/763.
Also adds a missing `const` qualification in one `_re_atomic_load`.
This is not tested on ARM. @alfredh, please, test if it compiles for you.
> atomic: Fix missing memory order arguments in MSVC atomic functions

- src/thread/thread.c
only available on newer systems
> thread: remove win32 SetThreadDescription 

- CHANGELOG.md
- CMakeLists.txt
- debian/changelog
- mk/Doxyfile
ABI bump is not needed, since only added functions:
```
Functions changes summary: 0 Removed, 0 Changed, 0 Added function
Variables changes summary: 0 Removed, 0 Changed, 0 Added variable
Function symbols changes summary: 0 Removed, 12 Added function symbols not referenced by debug info
Variable symbols changes summary: 0 Removed, 0 Added variable symbol not referenced by debug info
12 Added function symbols not referenced by debug info:
[A] http_sock_tls
[A] https_set_verify_msgh
[A] tls_set_posthandshake_auth
[A] tls_set_verify_client_handler
[A] tls_set_verify_client_trust_all
[A] tls_verify_client_post_handshake
[A] tmr_continue_dbg
[A] tmr_timespec_get
[A] uri_display_name_escape
[A] uri_escape
[A] uri_escape_pl
[A] vidmix_source_get_pidx
```
> release v3.1.0

- include/re_main.h
- src/main/main.c
- test/async.c
> main: add debug boolean to re_thread_check()

- CMakeLists.txt
> cmake: add optional static and shared build options

- test/test.c
extracted from this patch:
https://github.com/baresip/re/pull/758
> test: fix printf formating

- src/main/main.c
`re_lock()`/`re_unlock()` should only be needed if `re_main()` is running.
> main: add re_thread_enter/leave polling check

- include/rem_aubuf.h
- rem/aubuf/aubuf.c
This should make external overrun/underrun counting with remember of min/max
size obsolete.
> aubuf: activate overrun/underrun statistics

- include/re_uri.h
- src/sip/contact.c
- src/sip/ctrans.c
- src/sip/dialog.c
- src/sip/request.c
- src/uri/uric.c
- test/uri.c
Keep some API functions that could be useful for users of re.
This reverts commits:
- e03e282e743527b0f66c1a9c630462c97a561f87
- 5aaffb68aefcb56abb2cb3086bd3555a00efdae4
See BareSIP discussion for details: https://github.com/baresip/baresip/issues/2576
> revert uri escaping commits

- include/re_jbuf.h
- src/jbuf/jbuf.c
- test/jbuf.c
- test/test.c
- test/test.h
A video frame is usually divided into smaller packets. Since the rtp marker bit is not very reliable (packet can be lost) or has a different meaning for audio codecs (talk spurt), frames should be detected by timestamp after sequence deduplication and ordering.
> jbuf: refactor frame calculation

- .github/workflows/cmake_win.yml
related to: https://github.com/baresip/re/pull/780
Build openssl for either 32-bit or 64-bit intel.
no solution for ARM yet ...
> ci: compile choco openssl with --x86 for 32-bits

- src/hash/hash.c
- src/ice/chklist.c
- src/main/openssl.c
- src/pcp/request.c
- test/av1.c
- test/test.c
Command:
$ cppcheck -q -f --std=c99 --enable=warning .
> fix some cppcheck warnings

- src/base64/b64.c
Fixes:
```c
src/base64/b64.c:188:26: warning: Either the condition '!in' is redundant or there is pointer arithmetic with NULL pointer. [nullPointerArithmeticRedundantC
heck]                        
const char *in_end = in + ilen;
^ 
src/base64/b64.c:191:6: note: Assuming that condition '!in' is not redundant
if (!in || !out || !olen)                                                    
^  
src/base64/b64.c:188:26: note: Null pointer addition
const char *in_end = in + ilen;                                              
^
```
> base64: fix cppcheck warnings

- src/main/init.c
Prevent signal looping by unregistering instead of exiting to keep upper signal/coredump handling intact.
> main/init: fix upper signal handling

- rem/vidmix/vidmix.c
New defect(s) Reported-by: Coverity Scan
Showing 12 of 12 defect(s)
** CID 462177:  Concurrent data access violations  (MISSING_LOCK)
/rem/vidmix/vidmix.c: 71 in clear_all()
________________________________________________________________________________________________________ *** CID 462177:  Concurrent data access violations  (MISSING_LOCK) /rem/vidmix/vidmix.c: 71 in clear_all()
65     	struct le *le;
66
67     	for (le=mix->srcl.head; le; le=le->next) {
68
69     		struct vidmix_source *src = le->data;
70
>>>     CID 462177:  Concurrent data access violations  (MISSING_LOCK)
>>>     Accessing "src->clear" without holding lock "vidmix_source.mutex". Elsewhere, "vidmix_source.clear" is accessed with "vidmix_source.mutex" held 5 out of 6 times.
71     		src->clear = true;
72     	}
73 …
> vidmix: coverity fix

- src/sys/fs.c
*** CID 462173:  Resource leaks  (RESOURCE_LEAK)
Handle variable "fd" going out of scope leaks the handle.
> sys/fs: fix fs_stdio_hide resource leak

- include/re_sipreg.h
- src/sipreg/reg.c
- test/mock/sipsrv.c
- test/sipreg.c
- test/test.h
Not sure how safe it is changing the interfaces, using it to show what's the change needed for https://github.com/baresip/baresip/pull/2600/
Both re and baresip do build and test passed after the change.
> sipreg: supports PNS custom contact URI

- .github/workflows/ios.yml
- src/md5/wrap.c
Add building for iOS in CI:
* Xcode version 14
* OpenSSL is disabled
* Use Apple CommonCrypto api
> ci: add iOS platform

- src/jbuf/jbuf.c
A single video frame can be quite large, currently if a frame is larger than available packets, packets are silently dropped. This commit makes dropping more visible.
> jbuf: enable old frame drop warnings

- include/re_rtpext.h
- src/rtpext/rtpext.c
- test/rtpext.c
Add support for Two-Byte headers for RTP Header Extensions.
Reference: https://datatracker.ietf.org/doc/html/rfc8285
> rtpext: add support for Two-Byte headers

- src/sha/wrap.c
Add support for native Windows Wincrypt API for SHA functions.
This is similar to the MD5 commit: https://github.com/baresip/re/commit/1c6ac410ac5b2f91e609d534ae12187b38e27792
> sha: add support for Windows native API

- .github/workflows/cmake_win.yml
This is based on this PR: https://github.com/baresip/re/pull/780
It adds support for building on Windows ARM.
For this build configuration, OpenSSL is disabled and native crypto APIs are used.
> CI: Add support for building Windows ARM

- src/sip/request.c
This is the second part of #824.
Now, it is **not** configurable. The TCP source port is used in Contact header. In case of UDP the local listen port is used, like before.
Tested with TCP and UDP.
> sip: use TCP source port for Contact header

- CMakeLists.txt
https://github.com/baresip/re/pull/845
Thanks to Kai Pastor for review comment.
> cmake: remove obsolete $<INSTALL_INTERFACE:include for re-objs

- src/aes/stub.c
When building with
```
cd build
cmake -DUSE_OPENSSL=no ..
make
```
There are warnings that the parameters of functions in stub.c mismatch.
relates to: https://github.com/baresip/re/pull/871
> aes: correct parameters for stub

- src/fmt/time.c
copied from https://github.com/baresip/re/pull/758
> fmt: fix format string in fmt_timestamp()

- CMakeLists.txt
- cmake/FindMBEDTLS.cmake
- cmake/FindMbedTLS.cmake
- cmake/re-config.cmake
- src/hmac/hmac_sha1.c
- src/md5/wrap.c
- src/sha/wrap.c
- src/tls/stub.c
We are evaluating re/baresip on Cortex M7/M4 with Zephyr.
First step is to build re without TLS support. But at least the hash functions needs an MbedTLS backend.
Build with:
```
cd build
cmake -DUSE_OPENSSL=no ..
make
```
> hmac,md5,sha: add mbedtls backend

- include/re_httpauth.h
- src/httpauth/basic.c
- test/httpauth.c
- test/test.c
- test/test.h
+ create and encode HTTP Basic requests.
+ verify HTTP basic authentication header
+ test cases for httpauth_basic verification and request encoding
+ httpauth_basic is tested against wget, curl and an chromium based browser (Brave Browser)
> httpauth: basic challenge creation and verification functions

- include/re_tmr.h
This fixes an issue with cross-compiling and sysroot usage. It's the only patch I needed to add packages to Yocto for both libre and baresip.
> Fix include of re_thread.h in re_tmr.h

- src/sipsess/connect.c
- src/sipsess/listen.c
- src/sipsess/modify.c
- src/sipsess/update.c
- test/sipsess.c
- test/test.c
- test/test.h
According to [RFC 3261 section 12.1](https://www.rfc-editor.org/rfc/rfc3261#section-12.1)
```
2xx and 101-199 responses with a To tag, where the request was
INVITE, will establish a dialog.  A dialog established by a non-final
response to a request is in the "early" state and it is called an
early dialog.
```
This means that UPDATE (or INFO) requests are allowed within early dialogs (RFC 6086 mentions this in section 4.2.1, RFC 3311 in section 5.1).
However, UPDATEs with SDP offers or answers are still only allowed in "early confirmed dialogs" which have been confirmed by a PRACK (see RFCs 3311 and 6337).
> sipsess: allow UPDATE and INFO in early dialog

- src/main/init.c
Fixes build if HAVE_SIGNAL is not set.
e.g.
- RTOS
- zephyr
> main: use HAVE_SIGNAL in init.c

- src/sipsess/listen.c
Fixes a bug introduced in https://github.com/baresip/re/pull/878 which results in re-INVITEs not being accepted at all.
> sipsess/listen: Fix target_refresh_handler

- include/re_tls.h
- src/tls/stub.c
```
/home/alfredh/git/re/src/tls/openssl/tls.c:919: warning: argument 'pem' of command @param is not found in the argument list of tls_set_certificate(struct tls *tls, const char *cert, size_t len)
/home/alfredh/git/re/src/tls/openssl/tls.c:919: warning: The following parameter of tls_set_certificate(struct tls *tls, const char *cert, size_t len) is not documented:
parameter 'cert'
/home/alfredh/git/re/src/tls/openssl/tls.c:2100: warning: argument 'value' of command @param is not found in the argument list of tls_set_posthandshake_auth(struct tls *tls, int enabled)
/home/alfredh/git/re/src/tls/openssl/tls.c:2100: warning: The following parameter of tls_set_posthandshake_auth(struct tls *tls, int enabled) is not documented:
parameter 'enabled'
```
> tls: fix some doxygen warnings

- include/re_types.h
- test/CMakeLists.txt
- test/test.c
- test/test.h
- test/types.c
`cmake -B build -DCMAKE_BUILD_TYPE=Debug`
```c
int err;
re_assert(!(err = myfunc())); /* myfunc() is executed and assert() calls abort() if expr is false */
re_assert_se(!(err = myfunc())); /* myfunc() is executed and assert() calls abort() if expr is false  */
```
`cmake -B build -DCMAKE_BUILD_TYPE=Release`
```c
int err;
re_assert(!(err = myfunc())); /* myfunc() and assert() are not executed in release builds */
re_assert_se(!(err = myfunc())); /* myfunc() is executed in release build (keeps side effect) but assert() is not called */
```
> types: add re_assert and re_assert_se definition

- include/rem_aufile.h
- rem/aufile/aufile.c
Create two new functions:
- `aufile_get_size()`
- `aufile_get_length()`
The former returns the size in bytes, the latter the length in milliseconds.
> aufile: add methods to get size in bytes/length in ms

- include/re_types.h
- src/async/async.c
So worker callbacks can execute destructors etc.
> async: signal ESHUTDOWN to all open worker callbacks

- src/dns/client.c
This PR replaces the async getaddr dns query by a temporary one. So no locking is needed and the original query can safely destructed/aborted before async work is executed.
> dns/client: fix async getaddr query abort (not thread safe)

- src/async/async.c
- src/dns/client.c
`ECANCELED` is a much better error code for this use-case and dns query callback should also be called if available.
> async,dns/client: replace ESHUTDOWN with ECANCELED and optimize err handling

- src/ice/connchk.c
- src/ice/ice.h
- src/ice/icem.c
- src/ice/icesdp.c
Some browsers anonymize local webrtc sdp candidate ip addresses with mDNS `[UUID].local` (like "1bbabc05-80d2-4386-8e39-9666b53900d0.local"), this PR uses getaddrinfo to resolve these if needed.
TODO: 
refs https://github.com/baresip/baresip/discussions/2137
https://datatracker.ietf.org/doc/html/draft-ietf-mmusic-mdns-ice-candidates-03
Manual Testing:
- Start `baresip-webrtc -v`
- Open URL in Browser (private browser mode) Check `recvonly` (no microphone/camera permission) and connect
- You should see mDNS remote candidates:
```
{      audio. } mDNS remote cand: 4e712009-4a6c-40df-87a5-55bda80e6257.local
{      audio. } conncheck_start: waiting mDNS for remote candidate...
{      video. } mDNS remote cand: 4e712009-4a6c-40df-87a5-55bda80e6257.local
{      video. } conncheck_start: waiting …
```
> ice: add candidate sdp mdns support

- include/re_types.h
Variable argument lists are promoted to different types in C (default argument promotions).
| Type | promoted type |
| ------------- | ------------- |
| char, signed char, short  | int |
| unsigned char, unsigned short  | unsigned int  |
| float | double |
| bool (char) | int |
This PR fixes the sizes and improves size check
> types: fix RE_ARG_SIZE default argument promotions

- src/fmt/print.c
With normal printf you have to use something like this:
```c
#include <stdio.h>
#include <stdint.h>
#include <inttypes.h>
int main()
{
uint64_t t = 1;
printf("Value %" PRIu64 "\n", t);
return 0;
}
```
Since `uint64_t` can be `unsigned long int` -> `%lu` or `unsigned long long int` -> `%llu` on 32-bit wordsize plattforms.
This PR introduces `%L` to handle this:
```c
#include <re.h>
int main()
{
uint64_t t = 1;
re_printf("Value %Lu\n", t);
return 0;
}
```
> fmt/print: add 64-bit length modifier %Li, %Ld and %Lu

- include/re_types.h
- src/fmt/print.c
```c
#include <re.h>
int main(void)
{
re_printf("hello %s\n");
return 0;
}
```
Output: `print: Format: "hello %s<-- NO ARG`
```c
#include <re.h>
int main(void)
{
re_printf("hello %d\n", 1LL);
return 0;
}
```
Output: `print: Format: "hello %d<-- SIZE ERROR`
> fmt/print: improve print RE_VA_ARG debugging

- include/re_types.h
```c
#include <re.h>
int main(void)
{
struct pl r = {.p = "world",  str_len("world")};
re_printf("hello %r\n", r); /* common mistake needs pointer "&r" */
return 0;
}
```
`print: Format: "hello %r<-- SIZE ERROR`
> types: add RE_ARG_SIZE struct pl (avoids wrong print fmt %r usage)

- src/rtp/rtp.c
Fixes:
`print: Format: " Encode: seq=%u ssrc=0x%lx<-- SIZE ERROR`
> rtp/rtp_debug: fix printf size format

- cmake/re-config.cmake
Empty CMAKE_BUILD_TYPE is not equal to Debug build and can lead to missing debug symbols. Since cmake also support build configurations (for IDE's) it's better to set RELEASE definition by CONFIG generator expression.
> cmake/re-config: add default CMAKE_BUILD_TYPE and fix RELEASE definition

- src/dns/client.c
It's not fatal if getaddrinfo_h returns err, like not available 'AAAA' record.
> dns/client: use info for getaddrinfo_h err

- include/rem_aufile.h
- rem/aufile/aufile.c
This PR implements `aufile_set_position`, which sets the position in milliseconds.
> Implement aufile_set_position

- src/sip/dialog.c
See https://github.com/baresip/baresip/issues/2114.
> dialog: fix rtags of forking INVITE with 100rel

- src/tls/openssl/tls.c
For discussion, should we set a secure min. proto by default?
> tls/alloc: set default min proto TLS 1.2

- test/sdp.c
$ cppcheck --version
Cppcheck 2.12.0
```
$ cppcheck -q -f --std=c11 .
src/main/main.c:704:6: error: Uninitialized variable: n [uninitvar]
if (n < 0)
^
src/main/main.c:789:11: error: Uninitialized variable: fd [uninitvar]
index = fd;
^
src/sipevent/sipevent.h:51:39: error: syntax error [syntaxError]
void sipnot_refresh(struct sipnot *not, uint32_t expires);
^
test/sdp.c:367:9: warning: Uninitialized variable: err [uninitvar]
return err;
^
test/sdp.c:330:13: note: Assuming condition is false
for (i=0; i<RE_ARRAY_SIZE(msgs); i++) {
^
test/sdp.c:367:9: note: Uninitialized variable: err
return err;
^
```
> test: init err to 0 in sdp test (cppcheck)

- include/re_types.h
Works as expected on MacOS with clang
> Expand RE_BREAKPOINT macro on ARM64

- .gitignore
- src/main/init.c
- test/trace.c
Trace initialization should be handled by application (moving this to baresip)
> trace: remove global default trace json

- include/re_trace.h
Tracing should only enabled/disabled by `-DUSE_TRACE=ON` (default OFF).
> trace: use only explicit RE_TRACE_ENABLED by cmake

- CMakeLists.txt
Downstream patch:
https://github.com/microsoft/vcpkg/blob/master/ports/baresip-libre/use-c11.patch
> cmake: enable C11 for Windows (not MINGW)

- src/trace/trace.c
This reduces trace memory usage from ~137 MByte (1.000.000 entries) to 13,7 MByte (100.000 entries). Every second the trace buffer is flushed asynchronously if more than 1000 entries reached (`TRACE_FLUSH_THRESHOLD`).
All values can be overriden on compile time:
```c
-DCMAKE_C_FLAGS="-DTRACE_BUFFER_SIZE=10000 -DTRACE_FLUSH_THRESHOLD=100 -DTRACE_FLUSH_TMR=1000"
```
`TRACE_FLUSH_TMR` is in ms.
> trace: add flush worker and optimize memory usage

- include/re_rtp.h
- src/rtp/rtcp.h
- src/rtp/rtp.c
- src/rtp/sess.c
The receiver arrival time is useful for jitter handling and local playout time calculation. 
Fixing video jitter by calculating only when the timestamp is different than last packet (see RTP FAQ https://www.cs.columbia.edu/~hgs/rtp/faq.html#jitter).
> rtp: fix video jitter calculation and add arrival time rtp header

- include/re_trace.h
- src/trace/trace.c
Add identifier handling for custom id tracking like:
```json
{"cat":"jbuf","pid":490156,"tid":490156,"ts":1415394,"ph":"I","name":"flush","id":"call1_video"}
```
> trace: add id handling

- include/re_fmt.h
- src/fmt/pl.c
- test/fmt.c
- test/test.c
- test/test.h
`pl_alloc_str` is useful if you need a pl object that can also be referenced (`mem_ref`).
> fmt/pl: add pl_alloc_str

- src/sip/dialog.c
which broke common re-invite usage (hold/unhold).  See https://github.com/baresip/baresip/issues/2772.  I'll wait a couple of hours and if no other fix is provided, I'll merge this PR.  The most common re-invite use case must work.
> dialog: REVERT fix rtags of forking INVITE with 100rel (#947)

- src/ice/icesdp.c
> ice: AI_V4MAPPED doesn't exist on OpenBSD

- include/re_sipsess.h
- src/sipsess/sess.c
> test: call - add call on-hold/resume test

- src/async/async.c
Since we can't clear/revert a mqueue_push, free list handling has always be done by async `queueh` and not within `re_async_cancel`. Otherwise job is reused and maybe executed twice or early.
fixes #992
> async: fix re_async_cancel mqueue handling

- src/rtp/rtp.c
In github workflow got a sanitizer warning
https://github.com/cspiel1/baresip/actions/runs/6731606831/job/18301138986?pr=2
And I don't have an idea how to avoid this in upper layers (baresip rtprecv.c).
`rtcp_mux` is set from main thread and read from RX thread.
The `rtcp_mux` can change during the call is running by an SDP offer/answer challenge.
> rtp: make flag rtcp_mux atomic

- src/sip/transp.c
`tcp_conn_local_get` function does not always return information about the host address when the socket has been bound to an unspecified address.
fixes https://github.com/baresip/baresip/issues/2797
> sip/transp: add win32 local transport addr fallback

- CHANGELOG.md
- CMakeLists.txt
- debian/changelog
- mk/Doxyfile
- Press `Generate release notes` 
- Copy release notes to `CHANGELOG.md`
- `CMakeLists.txt`
- `include/baresip.h`
- `mk/Doxyfile`
- `CMakeLists.txt` (Bump PROJECT_SOVERSION)
- `CMakeLists.txt`
- libre
- baresip
- Maybe `Generate Release notes` is needed to update (delete last notes first)
- `CMakeLists.txt`
- `include/baresip.h` (baresip only)
- ~v3.6.0 18. Oct (@alfredh)~
- v3.7.0 22. Nov (@cspiel)
- v3.8.0 27. Dec (@sreimers)
> release v3.7.0

- src/sipsess/connect.c
According to RFC 3261, 100 responses can not create a dialog, so we MUST NOT do that.
This resulted in a bug because some proxies set a To tag in the 100 Trying response without sending a Contact header and we tried (and failed) to create a dialog from that.
> sipsess/connect: don't create a dialog for 100 responses

- src/trace/trace.c
Fixes around 4 warnings from Coverity 2023.6
```
145int re_trace_init(const char *json_file)
146{
147        int err = 0;
148
149#ifndef RE_TRACE_ENABLED
150        return 0;
151#endif
152
CID 469999: Structurally dead code (UNREACHABLE) [[select issue](https://scan8.scan.coverity.com/defectInstanceId=13589814&fileInstanceId=88291432&mergedDefectId=469999)]
153        if (!json_file)
154                return EINVAL;
155
156        if (re_atomic_rlx(&trace.init))
157                return EALREADY;
```
> trace: fix coverity warnings

- src/sipsess/connect.c
There are some SIP UAs which send 1XX responses with a To tag and without a Contact header.
This is enforced since v3.4.0 (#878) and with this change (#1028) we increase the compatibility with other SIP stacks while still staying compliant.
E.g. [Linphone only enforces](https://github.com/makinacorpus/linphone/blob/6979948c3eb1996c0e38e7a0fdcbcd10cc4dfa3d/coreapi/bellesip_sal/sal_op_call.c#L879C1-L888C3) sending of the Contact header when compiled with a special compile time option.
Further, [Kamailio removed the enforcing of this header too](https://github.com/kamailio/kamailio/issues/1720).
> connect: do not enforce Contact header in 1XX responses with To tag

- src/sip/dialog.c
Resolves: https://github.com/baresip/baresip/issues/2819
> dialog: fix rtags of forking INVITE

- .github/workflows/musl.yml
- CMakeLists.txt
- cmake/re-config.cmake
On some platforms linking atomic is needed.
> cmake: add RE_LIBS config and add atomic check

- include/re_sipsess.h
- src/sipsess/accept.c
- src/sipsess/connect.c
- src/sipsess/listen.c
- src/sipsess/modify.c
- src/sipsess/prack.c
- src/sipsess/reply.c
- src/sipsess/sess.c
- src/sipsess/sipsess.h
- src/sipsess/update.c
- test/sipsess.c
The SDP negotiation state is now tracked in a single enum which is used as a state machine to keep track of the current state of the SDP negotiation. This makes reasoning about the SDP negotiation much easier and less error prone.
Some details about SDP offer/answer are now enforced more strictly, e.g. the first reliable non-failure response to an INVITE **MUST** contain an SDP offer, if the INVITE contained no offer.
Read about SDP negotiation in the excellent informational [RFC 6337](https://www.rfc-editor.org/rfc/rfc6337).
> sipsess: refactor and simplify SDP negotiation state

- src/rtp/fb.c
- src/rtp/member.c
- src/rtp/pkt.c
- src/rtp/rr.c
- src/rtp/rtcp.c
- src/rtp/rtcp.h
- src/rtp/rtp.c
- src/rtp/sdes.c
- src/rtp/sess.c
- src/rtp/source.c
This PR makes the use of `struct rtp_source` thread safe.
The RX thread in baresip calls this functions from main thread
- rtcp_debug()
- rtcp_stats()
> rx thread activate

- test/rtp.c
- test/test.c
- test/test.h
cppcheck:
```
test/rtp.c:424:9: warning: Identical condition and return expression 'err', return value is always 0 [identicalConditionAfterEarlyExit]
return err;
^
test/rtp.c:417:6: note: If condition 'err' is true, the function will return/exit
if (err)
^
test/rtp.c:424:9: note: Returning identical expression 'err'
return err;
^
```
> test: move test_rtcp_decode_badmsg() to separate testcase

- src/rtp/fb.c
- src/rtp/member.c
- src/rtp/pkt.c
- src/rtp/rr.c
- src/rtp/rtcp.c
- src/rtp/rtcp.h
- src/rtp/rtp.c
- src/rtp/sdes.c
- src/rtp/sess.c
- src/rtp/source.c
We need to lock more fields of `rtcp_sess`.
This was found because of
```patch
commit 22bb762de43a895c57984f20dc1771f7529150ee
Author: Christian Spielberger <c.spielberger@commend.com>
Date:   Wed Jan 3 14:53:23 2024 +0100
test: call - concurrency test for audio_debug()
```
This PR removes the shortly added lock for `rtcp_source`. Instead the lock of `rtcp_sess` is used over larger code parts.
The concurrency test in baresip was intensified in order to find concurrency problems and possible deadlocks with a higher chance.
```patch
commit e267bb2d1655d2b93cbfce21648de47847bf7912 (HEAD -> rx_thread_activate, origin/rx_thread_activate)
Author: Christian Spielberger <c.spielberger@commend.com>
Date:   Thu Jan 4 14:09:34 2024 +0100
test: call - intensify RTCP/audio_debug concurrency test
```
> rtp: lock more fields from rtcp_sess

- .github/workflows/run-on-arch.yml
- CMakeLists.txt
This job uses QEMU to run a VM with ARM64-architecture.
Please note that the job is slow, around 4 minutes to complete.
> ci: add run-on-arch for ARM64 linux

- include/re_tmr.h
- src/tmr/tmr.c
If `tmr_cancel` is called from multiple threads it's enough to cancel once. The behavior remains undefined if `tmr_start` is called from multiple threads in parallel and should prevented by the caller.
> tmr: prevent race condition on cancel

- src/http/client.c
Fixes HTTP requests to IPv6ll adresses and if the local IPv6ll was set.
> http: client - set scopeid fixes HTTP requests for IPv6ll

- src/sip/transp.c
If `qentp` is set, the caller of `sip_transp_send` is responsible for derefing `qent`.
This caused undesirable behavior in the following scenario: A message is sent using `sip_transp_send` and the transport is TLS 1.3. The peer (i.e. server) requests a client certificate from us and then the server terminates the TLS and TCP connection (e.g. due to an invalid ceritificate). In this case, the caller of `sip_transp_send` never gets alerted that there was a transport error and some other timeout mechanism kicks in (e.g. in SIP 64 * T1). In BareSIP, this means e.g. that we start an outgoing call and the call stays in this outgoing call state for 32 seconds while the underlying TCP/TLS connection has long be terminated. Ideally, this transport error would immediately be propagated upwards. …
> transp: deref qent only if qentp is not set

- CMakeLists.txt
- include/re_fmt.h
- src/fmt/text2pcap.c
- src/fmt/time.c
- src/rtp/rtp.c
- src/trace/trace.c
- test/fmt.c
- test/test.c
- test/test.h
- test/trace.c
text2pcap is useful for debugging encrypted connections like DTLS_SRTP from application context.
See: https://blog.mozilla.org/webrtc/debugging-encrypted-rtp-is-more-fun-than-it-used-to-be/
```bash
jq -r ".traceEvents[] | select (.cat == \"pcap\") | .args.pcap" re_trace.json | text2pcap -D -n -l1 -i17 -u 1000,2000 -t '%H:%M:%S.%f' - dump.pcapng
```
Documentation: https://github.com/baresip/baresip/wiki/Text2pcap-RTP-and-RTCP-capturing
> misc: text2pcap helpers (RTP/RTCP capturing)

- include/re_tls.h
- src/sip/transp.c
- src/tls/openssl/tls.c
Per default, TLS client verification is disabled.
> transp,tls: add TLS client verification

- src/sipsess/listen.c
This implements the UAS behavior exactly as [RFC 3261 section 14.2](https://www.rfc-editor.org/rfc/rfc3261#section-14.2) states that it MUST be.
Specifically, the relevant section states
```
A UAS that receives a second INVITE before it sends the final
response to a first INVITE with a lower CSeq sequence number on the
same dialog MUST return a 500 (Server Internal Error) response to the
second INVITE and MUST include a Retry-After header field with a
randomly chosen value of between 0 and 10 seconds.
A UAS that receives an INVITE on a dialog while an INVITE it had sent
on that dialog is in progress MUST return a 491 (Request Pending)
response to the received INVITE.
```
> sipsess/listen: improve glare handling

- CHANGELOG.md
- CMakeLists.txt
- debian/changelog
- mk/Doxyfile
- Press `Generate release notes` 
- Copy release notes to `CHANGELOG.md`
- `CMakeLists.txt`
- `include/baresip.h`
- `mk/Doxyfile`
- `CMakeLists.txt` (Bump PROJECT_SOVERSION)
- `CMakeLists.txt`
- libre
- baresip
- Maybe `Generate Release notes` is needed to update (delete last notes first)
- `CMakeLists.txt`
- `include/baresip.h` (baresip only)
- ~v3.6.0 18. Oct (@alfredh)~
- ~v3.7.0 22. Nov (@cspiel1)~
- ~v3.8.0 27. Dec (@sreimers)~
- ~v3.9.0 31. Jan (@alfredh)~
- v3.10.0 6. Mar (@cspiel1)
- v3.11.0 10. Apr (@sreimers)
> release v3.10.0

- .github/workflows/clang-analyze.yml
- src/fmt/time.c
- test/httpauth.c
- test/sipsess.c
Fixes:
```c
test/httpauth.c:654:3: warning: Value stored to 'mb_printed' is never read
test/sipsess.c:216:2: warning: 1st function call argument is an uninitialized Value
test/sipsess.c:236:2: warning: 1st function call argument is an uninitialized Value
test/sipsess.c:535:2: warning: 1st function call argument is an uninitialized value
```
> ci/clang-analyze: bump clang version and fix status-bugs

- src/main/main.c
This fixes a potential memory leak in `fd_close`, if reallocating `mbuf` in `fhsld` delete list fails. Switching the delete list implementation to a single-linked list allows to avoid dynamic memory allocation (and the associated point of failure) in `fd_close`.
> main: Use slist for fhs delete list.

- src/http/server.c
replaced to a correct structure in sizeof
fixes #1080
> http/server: fix wrong sizeof in verify_msg

- .github/workflows/sanitizers.yml
`vm.mmap_rnd_bits` has been recently changed to 32 on GHA, which triggers issues in ASAN builds that spuriously fail on startup.
> ci/sanitizers: add mmap rnd_bits workaround

- src/thread/posix.c
Fixes (on arm32 gcc):
warning: cast from function call of type ‘int’ to non-matching type ‘void *’ [-Wbad-function-cast]
> thread/posix: optimize handler and fix gcc arm32 warning

- include/re_httpauth.h
- include/re_main.h
- src/httpauth/digest.c
- src/main/main.c
Fix 2 Parameter is different from the declaration.
Fix 1 Warning C4550: Expression evaluated as a function with missing parameter list
fixes: https://github.com/baresip/re/issues/1094
> main,httpauth: fix different from the declaration

- include/re_sip.h
- src/sip/request.c
- src/sipsess/sess.c
... if no provisional response was received for the request.
This caused the following undesirable behavior with UDP: A user starts a call, doesn't get a response and so the user cancels it. Shortly after, the recipient of the INVITE goes online, receives a UDP retransmission of the INVITE and sends a response. The user could suddenly be in a call they thought they cancelled.
With this change, if a SIP session is terminated, the underlying `request` and `ctrans` are destroyed immediately if no response was received at all.
For reliable transports this does not happen because a transport error would occur and there are no retransmissions.
> sess,request: deref request and ctrans immediately

- include/re_fmt.h
- include/re_sip.h
- src/fmt/pl.c
- pl: add pl_strncmp similar to strncmp of cstdlib
- re_sip: add Via branch id magic cookie constant
> ua: enforce magic cookie in Via branch

- include/re_sip.h
- src/sip/auth.c
- test/sipauth.c
Fixes https://github.com/baresip/baresip/issues/3006
Based on this PR:
https://github.com/baresip/re/pull/180
> sip/auth: SHA-256 digest algorithm support

- include/re_types.h
GCC workaround for bit fields (always default otherwise).
Ref: https://gcc.gnu.org/legacy-ml/gcc/2016-02/msg00266.html
> types: fix RE_ARG_SIZE gcc bit fields

- src/http/request.c
This fixes the following bug:
If a HTTP request is resent (e.g. with Authentication after a 401 response), the body of the request is not sent.
This is because in `req_body_handler` `mbuf_advance(conn->body, len)` is called. Then the request is re-sent and the body size is obtained by calling `mbuf_get_left(conn->body)` which is now incorrect.
The fix is to reset the `mbuf` position of `conn->body` before re-sending a request.
> http/request: reset body mbuf pos on re-sending

- src/http/client.c
The setters `http_client_set_certpem` and `http_client_set_keypem` pre-allocated a fixed size buffer of 512 byte. The required size is known at that time, so the correct size can be allocated right away and no resizing is needed in `mbuf_write_str`.
> http/client: use dynamically sized buffers for PEM setters

- src/tls/openssl/tls_tcp.c
- src/tls/openssl/tls_udp.c
With the current implementation, TLS renegotiations do not work, even if they are performed in a secure manner. With this change, TLS renegotiations are now possible if they are done in a secure manner (i.e. as described in [RFC 5746](https://www.rfc-editor.org/rfc/rfc5746)).
Read more about OpenSSL secure renegotiation [in the OpenSSL docs](https://www.openssl.org/docs/man3.2/man3/SSL_get_secure_renegotiation_support.html) (**SECURE RENEGOTIATION** section).
> tls: allow secure TLS renegotiation

- include/re_http.h
- include/re_tls.h
- src/http/client.c
- src/tls/openssl/tls.c
The current setters (e.g. `tls_set_certificate`) only allow single certificates to be set. Now the whole chain can be set.
> tls/http: add certificate chain setters

- src/sipsess/connect.c
Otherwise, if something in `invite_resp_handler` fails and `sipsess_terminate` is called, no BYE will be sent.
> sipsess/connect: set sess->established immediately on 200 receival

- include/re_sip.h
- src/sip/dialog.c
- src/sipsess/connect.c
Note that `lseq` could not be used because there might be PRACKs sent which increment the CSeq and would cause a mismatch.
> sip: verify call-id, to-tag, cseq of INVITE response

- src/tls/openssl/sni.c
- src/tls/openssl/tls.c
- src/tls/openssl/tls.h
Replaces unsupported (by LibreSSL) `SSL_certs_clear` with recommended `SSL_set_SSL_CTX()`:
https://www.openssl.org/docs/man3.3/man3/SSL_CTX_set_tlsext_servername_callback.html
> The servername callback should return one of the following values:
> 
> SSL_TLSEXT_ERR_OK
> This is used to indicate that the servername requested by the client has been accepted. Typically a server will call SSL_set_SSL_CTX() in the callback to set up a different configuration for the selected servername in this case.
> tls: refactoring SNI ctx usage for libressl support

- include/re_sip.h
- src/sip/request.c
- src/sip/sip.c
fixes #1140 - Stateless SIP requests with TLS transport fail with EINVAL
> sip: add host param to sip_send_conn

- CHANGELOG.md
- CMakeLists.txt
- debian/changelog
- mk/Doxyfile
- Press `Generate release notes` 
- Copy release notes to `CHANGELOG.md`
- `CMakeLists.txt`
- `include/baresip.h`
- `mk/Doxyfile`
- `CMakeLists.txt` (Bump PROJECT_SOVERSION)
- `CMakeLists.txt`
- libre
- baresip
- Maybe `Generate Release notes` is needed to update (delete last notes first)
- `CMakeLists.txt`
- `include/baresip.h` (baresip only)
- ~v3.12.0 15. May (@alfredh)~
- v3.13.0 19. Jun (@cspiel1)
- v3.14.0 24. Jul (@sreimers)
> release v3.13.0

- src/sipreg/reg.c
Currently, REGISTERs are retried until the loop detection mechanism kicks in, which results in 16 unsuccessful REGISTERs being sent in very quick succession if the REGISTER can't be authorized (401 or 407 responses).
Now, on 401 and 407 responses, the REGISTER is only retried once (instead of 16 times). Re-trying the same request 16 times with the same auth credentials doesn't make much sense.
> sipreg/reg.c: stop retrying registers early after 401/407

- test/sipauth.c
cppcheck warning:
```
test/sipauth.c:129:6: warning: Uninitialized variable: err [uninitvar]
if (err) {
^
test/sipauth.c:95:23: note: Assuming condition is false
for (size_t i = 0; i < RE_ARRAY_SIZE(testv); i++) {
^
test/sipauth.c:129:6: note: Uninitialized variable: err
if (err) {
^
```
> test: init err in test_sip_auth_encode()

- src/udp/mcast.c
For IPv6 (link-local) the interface must be selected when sending packets. Otherwise, `udp_setsockopt()` results in an ICMPv6 packet being sent with the source IP being `::` which results in IPv6 multicast not working.
> udp/mcast: use group scopeid as interface for IPv6

- .clangd
Necessary if the chosen compiler is not clang but clangd is used as a language server.
> .clangd: suppress -Wgnu-zero-variadic-macro-arguments

- src/sipsess/reply.c
RFC 3261 [section 13.3.1.4](https://www.rfc-editor.org/rfc/rfc3261#section-13.3.1.4):
```
If the server retransmits the 2xx response for 64*T1 seconds without
receiving an ACK, the dialog is confirmed, but the session SHOULD be
terminated.  This is accomplished with a BYE, as described in Section
15.
```
If we never receive an ACK, the `sipsess` will never be cleaned up.
> sipsess/reply: terminate session if no (PR)ACK received after 64*T1

- src/dns/rr.c
found by coverity:
```
CID 400048: (#1 of 1): Overflowed constant (INTEGER_OVERFLOW)
6. overflow_const: Expression n--, which is equal to 18446744073709551615, where n is known to be equal to 0, underflows the type that receives it, an unsigned integer 64 bits wide.
```
> dns/rr: fix dns_rr_print underflow

- test/async.c
If test system has no IPv4 address (besides localhost) getaddrinfo returns error.
fixes #1164
> test/async: remove AI_ADDRCONFIG

- test/main.c
The current options aren't reflected by the current usage message anymore, thus use same message style like in baresip's selftest.
> retest: update usage message

- include/re_sip.h
- src/sip/transp.c
transp.c: add sip_transp_add_sock
to add SIP transport protocol without opening a listening socket (UDP socket is always opened).
Related:
- https://github.com/baresip/baresip/pull/3080
> add filter_registrar option

- src/tls/openssl/sni.c
The servername_callback is also called when the server requests a certificate in the ServerHello. However, the server will not usually send us the server_name extension. So skip the SNI check if we are client. Also continue if the server_name extension is not present.
> tls/sni: skip SNI check if we are client or server_name absent

- src/tls/openssl/sni.c
Currently, whenever a TLS handshake message is received and SNI certificate matching is done, TLS peer verification is also enabled. This ignores settings like verify_server and verify_client in the tls struct and is not needed. Therefore, the call to explicitly enable peer verification as part of SNI is removed.
> tls/sni: do not enable client verification when SNI matching is done

- CMakeLists.txt
- include/re_dd.h
- include/re_h264.h
- src/av1/getbit.c
- src/dd/dd.c
- src/dd/dd_enc.c
- src/dd/putbit.c
- src/h264/getbit.c
- src/h264/h264.h
- test/CMakeLists.txt
- test/dd.c
- test/test.c
- test/test.h
Defined in:
https://aomediacodec.github.io/av1-rtp-spec/#dependency-descriptor-rtp-header-extension
This work was sponsored by Nvidia Corporation
> dd: Dependency Descriptor RTP header extension

- include/rem_aubuf.h
- include/rem_auframe.h
- rem/aubuf/aubuf.c
- rem/auframe/auframe.c
`cmake -B build -DUSE_TRACE=ON -DCMAKE_C_FLAGS="-DAUBUF_TRACE"`
> aubuf: add AUBUF_TRACE mode with id

- src/sipsess/reply.c
fixes #1178 - `mem_deref(sess)` calls maybe `list_flush(&sess->replyl)` within destructor and reply is a dangling pointer after this.
> sipsess/reply: fix heap-use-after-free bug

- src/ice/icesdp.c
AI_V4MAPPED macro is missing on some platforms, e.g. OpenBSD, NetBSD, etc.
> ice: AI_V4MAPPED macro is missing on some BSD systems

- include/re_rtp.h
- src/rtp/rtcp.c
- test/rtcp.c
> rtp/rtcp: add RTCP Generic NACK packet send (RFC 4585 6.2.1)

- CHANGELOG.md
- CMakeLists.txt
- debian/changelog
- mk/Doxyfile
checklist: https://github.com/baresip/re/wiki/Release-Checklist
> release v3.16.0

- include/re_dns.h
- src/dns/client.c
- src/sip/request.c
On current Android and iOS platforms, access to the system DNS server lists is restricted (e.g. https://developer.android.com/about/versions/oreo/android-8.0-changes.html#o-pri). Even when it is available, it is often broken in certain situations (e.g. https://forums.developer.apple.com/forums/thread/75449). It is therefore practically impossible to perform manual DNS queries as `re` typically does for SIP.
Currently, `re` partially supports these platforms by offering the option to use `getaddrinfo`, but even this fails when no DNS servers are known due to `/etc/resolv.conf` not being accessible. Note that manually specifying 'well-known' DNS servers like `8.8.8.8` is not an acceptable workaround for private networks. Nor is it acceptable to manually specify a fixed private DNS, IT …
> dnsc: Fallback to getaddrinfo without any DNS servers

- CMakeLists.txt
- include/re_thread.h
- src/thread/win32.c
- test/CMakeLists.txt
- test/thread.c
GetCurrentThread() returns only a pseudo handle and can not used
within other threads
Fixes #1202
> thread: fix thrd_equal win32 handle

- CMakeLists.txt
- include/re_types.h
> types: fix clang-tidy warning (gcc bit fields workaround)

- include/re_odict.h
- src/odict/entry.c
- test/odict.c
- test/test.c
- test/test.h
> odict: add odict_pl_add()

- .github/workflows/build.yml
Use same versions of Linux distributions like at https://github.com/baresip/baresip/pull/3193 and synchronize GCC version usage, too.
> ci/build: remove Ubuntu 20.04, add 24.04, use GCC 14 on 24.04

- test/test.c
```
alfredh@debian:~/git/re$ ./test/retest -v -i
retest: libre version 3.17.0 (x86_64/Linux)
using async polling method 'epoll'
using datapath './test/data'
integration tests
test_dns_cache_http_integration : OK	
test_dns_http_integration       : OK	
test_dns_integration            : OK	
test_net_dst_source_addr_get    : OK	
test_rtp_listen                 : OK	
test_sip_drequestf_network      : OK	
test_sipevent_network           : OK	
test_sipreg_tcp                 : OK	
test_sipreg_tls                 : OK	
test_sipreg_udp                 : OK	
test_tmr_jiffies                : OK	
test_tmr_jiffies_usec           : OK	
test_turn_thread                : main: fd_close err: fd=4 (No such file or directory [2])
OK	
test_thread_cnd_timedwait       : OK	
```
> test: vertical alignment of integration test names

- test/http.c
Improves performance of test/http: https://github.com/baresip/re/issues/1211
> test/http: decrease test runs from 20 to 3 to decrease test time

- src/sip/transp.c
A customer reports problems with their SIP proxy that misses the Max-Forwards header for SIP MESSAGE. Our devices reject these SIP requests.
In RFC 3261 couldn't find anything about what a UAC should do with a SIP request without a Max-Forwards header.
Found this about SIP Proxy:
```
16 Proxy Behavior
16.3 Request Validation
3. Max-Forwards check
If the request does not contain a Max-Forwards header field, this
check is passed.
```
Which is the opposite of the current behavior.
@juha-h @alfredh @sreimers Do you agree with removing the check?
> sip/transp: allow requests w/o Max-Forwards header

- src/rtp/rtcp.c
- src/rtp/rtcp.h
- src/rtp/sess.c
According to [RFC 3550 section 6.1](https://www.rfc-editor.org/rfc/rfc3550#section-6.1) all RTCP packets MUST be sent as compound packets:
```
Thus, all RTCP packets MUST be sent in a compound packet of at least
two individual packets, with the following format:
...
SR or RR:  The first RTCP packet in the compound packet MUST
always be a report packet to facilitate header validation as
described in Appendix A.2.  This is true even if no data has been
sent or received, in which case an empty RR MUST be sent, and even
if the only other RTCP packet in the compound packet is a BYE.
...
SDES:  An SDES packet containing a CNAME item MUST be included
in each compound RTCP packet, except as noted in Section 9.1.
```
With this change, RTCP packets sent with `rtcp_quick_send` are now sent as …
> rtp: send all RTCP packets as compound packets

- src/rtp/sess.c
Fixes https://github.com/baresip/baresip/issues/3233
> rtp/sess.c: lock rtcp_sess in rtcp_set_srate_tx to fix data race

- include/re_sipsess.h
- src/sipsess/sess.c
Used for: https://github.com/baresip/baresip/pull/3236
> sipsess: add sipsess_msg getter function

- src/rtp/sess.c
Found by coverity:
> CID 443862:  Concurrent data access violations  (MISSING_LOCK) Accessing "sess->srate_tx" without holding lock "rtcp_sess.lock". Elsewhere, "rtcp_sess.srate_tx" is written to with "rtcp_sess.lock" held 2 out of 2 times (2 of these accesses strongly imply that it is necessary).
> rtp/sess: fix missing srate_tx locking

- CMakeLists.txt
- include/re_net.h
- src/net/linux/addrs.c
- src/net/linux/macros.h
- src/net/linux/rt.c
- src/net/net.c
This pull request adds support for obtaining network interface addresses using the RTNETLINK API on Linux systems.
fixes https://github.com/baresip/baresip/issues/3245
> net/linux: add net_netlink_addrs

- src/sys/fs.c
Not very likely to happen (since errno must be zero) but fixes clang-analyze warnings
> sys/fs: fix fs_fopen return null check

- src/rtp/fb.c
- src/rtp/rtcp.h
SLI is not used in our stack.
Also contributes to increased code coverage.
> rtp: remove rtcp_psfb_sli_encode() (unused)

- src/net/linux/addrs.c
For point-to-point interfaces IFA_ADDRESS points to the peer address instead of the local address.
>  Important comment:
>  IFA_ADDRESS is prefix address, rather than local interface address.
>  It makes no difference for normally configured broadcast interfaces,
>  but for point-to-point IFA_ADDRESS is DESTINATION address,
>  local address is supplied in IFA_LOCAL attribute.
>
> net/linux/addrs: fix point-to-point peer address bug

- src/net/linux/addrs.c
Fixes: `netlink: 4 bytes leftover after parsing attributes in process 'baresip'.` messages
> net/linux/addrs: fix netlink kernel warnings

- include/rem_vid.h
- include/rem_vidconv.h
- rem/vidconv/vconv.c
- rem/vidmix/vidmix.c
- test/vidconv.c
Improved layout for two and three participants (full centred scaled view).
> rem/vidconv: add vidconv_center and x and y source offsets

- include/re_mem.h
- src/mem/mem.c
DRAFT and Proposal
This is a proposal to remove the "peak" calculations
> mem: remove peak from memstat

- src/net/if.c
- src/net/linux/addrs.c
> net/linux/addrs: use list instead of fixed array for interface up

- include/re_atomic.h
original error for C++ file on Windows-ARM64:
```
C:\PROGRA~1\MICROS~2\2022\ENTERP~1\VC\Tools\MSVC\1442~1.344\bin\Hostx64\arm64\cl.exe  /nologo /TP -DARCH=\"AMD64\" -DHAVE_ATOMIC -DHAVE_IO_H -DHAVE_PQOS_FLOWID -DHAVE_QOS_FLOWID -DHAVE_SELECT -DHAVE_UNIXSOCK=1 -DOS=\"Windows\" -DRE_VERSION=\"3.18.0\" -DVER_MAJOR=3 -DVER_MINOR=18 -DVER_PATCH=0 -DWIN32 -D_CRT_SECURE_NO_WARNINGS -D_GNU_SOURCE -D_WIN32_WINNT=0x0600 -Dretest_EXPORTS -ID:\a\re\re\test\. -ID:\a\re\re\include /DWIN32 /D_WINDOWS /EHsc /Ob0 /Od /RTC1 -MDd -Zi /W3 /showIncludes /Fotest\CMakeFiles\retest.dir\cplusplus.cpp.obj /Fdtest\CMakeFiles\retest.dir\ /FS -c D:\a\re\re\test\cplusplus.cpp D:\a\re\re\include\re_atomic.h(602): error C2664: 'char __iso_volatile_load8(volatile const char *)': cannot convert argument 1 from 'const …
```
> atomic: fix compilation for C++ and Windows-ARM64

- .github/workflows/cmake_win.yml
- .github/workflows/sanitizers.yml
- CMakeLists.txt
- include/re_atomic.h
- test/CMakeLists.txt
- test/cplusplus.cpp
- test/test.c
- test/test.h
Proposal to compile a C++ application to test libre api.
There are some build errors for ARM64-Windows:
```
FAILED: test/CMakeFiles/retest.dir/cplusplus.cpp.obj 
C:\PROGRA~1\MICROS~2\2022\ENTERP~1\VC\Tools\MSVC\1442~1.344\bin\Hostx64\arm64\cl.exe  /nologo /TP -DARCH=\"AMD64\" -DHAVE_ATOMIC -DHAVE_IO_H -DHAVE_PQOS_FLOWID -DHAVE_QOS_FLOWID -DHAVE_SELECT -DHAVE_UNIXSOCK=1 -DOS=\"Windows\" -DRE_VERSION=\"3.18.0\" -DVER_MAJOR=3 -DVER_MINOR=18 -DVER_PATCH=0 -DWIN32 -D_CRT_SECURE_NO_WARNINGS -D_GNU_SOURCE -D_WIN32_WINNT=0x0600 -Dretest_EXPORTS -ID:\a\re\re\test\. -ID:\a\re\re\include /DWIN32 /D_WINDOWS /EHsc /Ob0 /Od /RTC1 -MDd -Zi /W3 /showIncludes /Fotest\CMakeFiles\retest.dir\cplusplus.cpp.obj /Fdtest\CMakeFiles\retest.dir\ /FS -c D:\a\re\re\test\cplusplus.cpp …
```
> test: add test for C++ applications

- src/http/client.c
Timeout on receiving no more chunks.
> http: restart timer for each chunk

- include/re_rtpext.h
- src/rtpext/rtpext.c
Finds an RTP extension by its ID within an array of RTP extensions (moved from baresip)
> rtpext: add rtpext_find

- include/re_list.h
- src/list/list.c
Instead of iterating over the list, count items separately
> list: optimize list_count

- CMakeLists.txt
- mk/Doxyfile
I guess we should also bump SOVERSION because of the `struct list` change ?
There might be a problem with the abidiff job ...
> bump version to 3.21.0

- include/re_av1.h
- src/av1/pkt.c
- test/av1.c
The AV1 packetizer did not properly packetize all AV1 bitstreams. It incorrectly calculated the "w" field from the AV1 RTP spec once and applied it to all RTP packets. This field needs to be determined on a per-packet basis. In practice, this meant the packetizer generated invalid RTP packets if w = 0 for the first packet (i.e. 4 or more OBUs).
Rewrite the packetizer to accurately determine how many OBU fragments are present in each RTP packet. The general idea is:
1. Start with the first OBU in the user buffer
2. Fill the RTP packet with data from the current OBU
3. If there is space left over in the packet, move to the next OBU and repeat #2
4. Once the RTP packet is full, report it to the handler and clear it and repeat #2
Update the tests to get wider coverage of this new algorithm. …
> Handle "w" properly in the AV1 packetizer

- .github/workflows/build.yml
Annotations
2 warnings:
ninja 1.12.1 is already installed and up-to-date. To reinstall 1.12.1, run: brew reinstall ninja
> ci: remove step to install ninja on macOS

- src/tls/openssl/tls.c
src/tls/openssl/tls.c:509:8: warning: assigning to 'X509_PURPOSE *' (aka 'struct x509_purpose_st *') from 'const X509_PURPOSE *' (aka 'const struct x509_purpose_st *') discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
xptmp = X509_PURPOSE_get0(i);
^ ~~~~~~~~~~~~~~~~~~~~
1 warning generated.
LibreSSL from MacPorts:
libressl @4.1.0_0 (active)
> tls: fix compiler warning with libressl 4.1.0

- src/http/server.c
all timers must be cancelled in the destructor with `tmr_cancel()`
otherwise if the timer does not fire, and the object goes out of scope,
the timer system will point to garbage memory.
> http: cancel verify_cert_tmr and skip init

- src/tls/openssl/tls.c
SSL_SESSION_is_resumable() returns 1 if the session is resumable or 0 otherwise.
It always returns 0 with LibreSSL.
> tls: fix SSL_SESSION_is_resumable LibreSSL

- include/re_sip.h
- src/sip/dialog.c
Hello this relates to baresip issue [#3367](https://github.com/baresip/baresip/issues/3367).
Exposing ltag and rtag is the approach I took to retrieve tags in baresip's call_replace_transfer. I plan to go ahead with the PR for baresip once this is done. Is that ok? 
This is my first experience with contributing to an open source project. Please let me know should anything else be needed.
> sip: exposed ltag and rtag in sip dialog

- include/re_h265.h
- src/h265/nal.c
- test/h265.c
- update h265_is_keyframe() to include H265_NAL_RSV_IRAP_VCL{22,23}
- IRAP = Intra Random Access Pictures
See:
https://www.ffmpeg.org/doxygen/2.2/libavcodec_2hevc_8h.html#aef033ac1a8e8b14e8bceb15e9c4f2df3
> h265: add H265_NAL_RSV_IRAP_VCL{22,23}

- test/httpauth.c
fixes: https://github.com/baresip/re/issues/1330
Checked that `resp->response` is a null-terminated string because in `src/httpauth/digest.c:927` `re_snprintf()` is used.
> test/httpauth: fix debug warning for digest response

- test/async.c
This test fails on Android where `getaddrinfo` does not accept AI_V4MAPPED: https://stackoverflow.com/questions/39674147/getaddrinfo-on-android-returning-error-eai-badflags
Since this test isn't really related to socket functionality, disable use of `AI_V4MAPPED` when running on Android. Note a similar issue with this test was previously dealt with in #1164.
Extracted from #1329.
> test/async: Remove unsupported AI_V4MAPPED on Android

- CMakeLists.txt
- cmake/re-config.cmake
Baresip's default out-of-the-box networking currently doesn't work well on Android when IPv6-only due to inability to enumerate IPv6-only network interfaces. This appears to be because `ifaddrs` support is currently disabled. There are APIs to manually add interfaces to Baresip but this requires more advanced integration with the Java API in Android.
Android added `ifaddrs` support in API level 24 (Android 7) which was ages ago:
https://android.googlesource.com/platform/bionic/+/master/libc/include/ifaddrs.h#81
This PR allows `ifaddrs` to be used on Android API >= 24 so that the built-in Baresip networking works with IPv6-only networks.
I have enabled it and tested that with this change, Baresip can successfully use `getifaddrs` on a non-rooted Android 13 phone to enumerate IPv6-only …
> net: Support ifaddrs on Android API level >= 24

- src/rtp/rr.c
Using left shift on a uint8_t promotes it to a signed integer. Casting
to uint32_t fixes this.
> rtp/rr: fix fraction left shift promotion

- .github/workflows/run-on-arch.yml
- README.md
- src/tls/openssl/tls.c
Since we release a major version, it's maybe a good time to drop OpenSSL 1.1.1 support.
> tls: drop OpenSSL 1.1.1 support

- rem/aubuf/ajb.c
- rem/aubuf/ajb.h
Please take a look at this PR.
It looks like the private function in AJB `plot_underrun()` is not used anywhere.
Proposal to remove it or start using it if that was a bug.
> aubuf: remove unused private function plot_underrun()

- include/re_websock.h
- src/websock/websock.c
- test/websock.c
* Remove unused websock_peer()
* Increase payload size to test different encoding
* Enable keepalive with 1 milliseconds interval
> websock: increase test coverage

- test/udp.c
Test UDP on both IPv4 and IPv6
> test: add support for IPv6 on UDP-test

- .github/workflows/cmake_win.yml
Run retest also when compiled without OpenSSL support
> ci: enable Windows testing when OpenSSL is disabled

- include/re_tls.h
- src/tls/openssl/tls.c
- src/tls/stub.c
Proposal to remove tls_set_certificate_der().
It is probably unused. Use PEM certificates instead.
> tls: remove tls_set_certificate_der() -- unused

- include/re_tls.h
- src/tls/openssl/tls.c
enum is passed by value, no need for const
> tls: tls_set_resumption() -- change const enum to enum

- include/re_ice.h
- src/ice/icem.c
If mDNS candidates needs to be resolved, checking `icem_rcandl` is not enough. So application never starts `icem_conncheck_start`.
> ice/icem: add icem_rcand_ready helper

- src/tls/openssl/sni.c
this was causing the baresip CI to fail ..
> tls: revert wrong match-checking in SNI function
